// Code generated by protoc-gen-go. DO NOT EDIT.
// source: charonrpc/refresh_token.proto

package charonrpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	ntypes "github.com/piotrkowalczuk/ntypes"
	qtypes "github.com/piotrkowalczuk/qtypes"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RefreshToken struct {
	Token                string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Notes                *ntypes.String       `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Disabled             bool                 `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ExpireAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	LastUsedAt           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *ntypes.Int64        `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *ntypes.Int64        `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{0}
}

func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (m *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(m, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshToken) GetNotes() *ntypes.String {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *RefreshToken) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RefreshToken) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *RefreshToken) GetExpireAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

func (m *RefreshToken) GetLastUsedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUsedAt
	}
	return nil
}

func (m *RefreshToken) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RefreshToken) GetCreatedBy() *ntypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *RefreshToken) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RefreshToken) GetUpdatedBy() *ntypes.Int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

type RefreshTokenQuery struct {
	UserId               *qtypes.Int64     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Notes                *qtypes.String    `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	Disabled             *ntypes.Bool      `protobuf:"bytes,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ExpireAt             *qtypes.Timestamp `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	LastUsedAt           *qtypes.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt            *qtypes.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *qtypes.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RefreshTokenQuery) Reset()         { *m = RefreshTokenQuery{} }
func (m *RefreshTokenQuery) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenQuery) ProtoMessage()    {}
func (*RefreshTokenQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{1}
}

func (m *RefreshTokenQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenQuery.Unmarshal(m, b)
}
func (m *RefreshTokenQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenQuery.Marshal(b, m, deterministic)
}
func (m *RefreshTokenQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenQuery.Merge(m, src)
}
func (m *RefreshTokenQuery) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenQuery.Size(m)
}
func (m *RefreshTokenQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenQuery proto.InternalMessageInfo

func (m *RefreshTokenQuery) GetUserId() *qtypes.Int64 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *RefreshTokenQuery) GetNotes() *qtypes.String {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *RefreshTokenQuery) GetDisabled() *ntypes.Bool {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *RefreshTokenQuery) GetExpireAt() *qtypes.Timestamp {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

func (m *RefreshTokenQuery) GetLastUsedAt() *qtypes.Timestamp {
	if m != nil {
		return m.LastUsedAt
	}
	return nil
}

func (m *RefreshTokenQuery) GetCreatedAt() *qtypes.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RefreshTokenQuery) GetUpdatedAt() *qtypes.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateRefreshTokenRequest struct {
	Notes                *ntypes.String       `protobuf:"bytes,1,opt,name=notes,proto3" json:"notes,omitempty"`
	ExpireAt             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateRefreshTokenRequest) Reset()         { *m = CreateRefreshTokenRequest{} }
func (m *CreateRefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRefreshTokenRequest) ProtoMessage()    {}
func (*CreateRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{2}
}

func (m *CreateRefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRefreshTokenRequest.Unmarshal(m, b)
}
func (m *CreateRefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateRefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRefreshTokenRequest.Merge(m, src)
}
func (m *CreateRefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRefreshTokenRequest.Size(m)
}
func (m *CreateRefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRefreshTokenRequest proto.InternalMessageInfo

func (m *CreateRefreshTokenRequest) GetNotes() *ntypes.String {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *CreateRefreshTokenRequest) GetExpireAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

type CreateRefreshTokenResponse struct {
	RefreshToken         *RefreshToken `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateRefreshTokenResponse) Reset()         { *m = CreateRefreshTokenResponse{} }
func (m *CreateRefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRefreshTokenResponse) ProtoMessage()    {}
func (*CreateRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{3}
}

func (m *CreateRefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRefreshTokenResponse.Unmarshal(m, b)
}
func (m *CreateRefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateRefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRefreshTokenResponse.Merge(m, src)
}
func (m *CreateRefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRefreshTokenResponse.Size(m)
}
func (m *CreateRefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRefreshTokenResponse proto.InternalMessageInfo

func (m *CreateRefreshTokenResponse) GetRefreshToken() *RefreshToken {
	if m != nil {
		return m.RefreshToken
	}
	return nil
}

type ListRefreshTokensRequest struct {
	Offset               *ntypes.Int64      `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                *ntypes.Int64      `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy              []*Order           `protobuf:"bytes,3,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Query                *RefreshTokenQuery `protobuf:"bytes,11,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRefreshTokensRequest) Reset()         { *m = ListRefreshTokensRequest{} }
func (m *ListRefreshTokensRequest) String() string { return proto.CompactTextString(m) }
func (*ListRefreshTokensRequest) ProtoMessage()    {}
func (*ListRefreshTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{4}
}

func (m *ListRefreshTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRefreshTokensRequest.Unmarshal(m, b)
}
func (m *ListRefreshTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRefreshTokensRequest.Marshal(b, m, deterministic)
}
func (m *ListRefreshTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRefreshTokensRequest.Merge(m, src)
}
func (m *ListRefreshTokensRequest) XXX_Size() int {
	return xxx_messageInfo_ListRefreshTokensRequest.Size(m)
}
func (m *ListRefreshTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRefreshTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRefreshTokensRequest proto.InternalMessageInfo

func (m *ListRefreshTokensRequest) GetOffset() *ntypes.Int64 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ListRefreshTokensRequest) GetLimit() *ntypes.Int64 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListRefreshTokensRequest) GetOrderBy() []*Order {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListRefreshTokensRequest) GetQuery() *RefreshTokenQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type ListRefreshTokensResponse struct {
	RefreshTokens        []*RefreshToken `protobuf:"bytes,1,rep,name=refresh_tokens,json=refreshTokens,proto3" json:"refresh_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListRefreshTokensResponse) Reset()         { *m = ListRefreshTokensResponse{} }
func (m *ListRefreshTokensResponse) String() string { return proto.CompactTextString(m) }
func (*ListRefreshTokensResponse) ProtoMessage()    {}
func (*ListRefreshTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{5}
}

func (m *ListRefreshTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRefreshTokensResponse.Unmarshal(m, b)
}
func (m *ListRefreshTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRefreshTokensResponse.Marshal(b, m, deterministic)
}
func (m *ListRefreshTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRefreshTokensResponse.Merge(m, src)
}
func (m *ListRefreshTokensResponse) XXX_Size() int {
	return xxx_messageInfo_ListRefreshTokensResponse.Size(m)
}
func (m *ListRefreshTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRefreshTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRefreshTokensResponse proto.InternalMessageInfo

func (m *ListRefreshTokensResponse) GetRefreshTokens() []*RefreshToken {
	if m != nil {
		return m.RefreshTokens
	}
	return nil
}

type DisableRefreshTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRefreshTokenRequest) Reset()         { *m = DisableRefreshTokenRequest{} }
func (m *DisableRefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRefreshTokenRequest) ProtoMessage()    {}
func (*DisableRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{6}
}

func (m *DisableRefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRefreshTokenRequest.Unmarshal(m, b)
}
func (m *DisableRefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *DisableRefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRefreshTokenRequest.Merge(m, src)
}
func (m *DisableRefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRefreshTokenRequest.Size(m)
}
func (m *DisableRefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRefreshTokenRequest proto.InternalMessageInfo

func (m *DisableRefreshTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DisableRefreshTokenRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DisableRefreshTokenResponse struct {
	RefreshToken         *RefreshToken `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DisableRefreshTokenResponse) Reset()         { *m = DisableRefreshTokenResponse{} }
func (m *DisableRefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DisableRefreshTokenResponse) ProtoMessage()    {}
func (*DisableRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5540bd1101661962, []int{7}
}

func (m *DisableRefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRefreshTokenResponse.Unmarshal(m, b)
}
func (m *DisableRefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *DisableRefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRefreshTokenResponse.Merge(m, src)
}
func (m *DisableRefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DisableRefreshTokenResponse.Size(m)
}
func (m *DisableRefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRefreshTokenResponse proto.InternalMessageInfo

func (m *DisableRefreshTokenResponse) GetRefreshToken() *RefreshToken {
	if m != nil {
		return m.RefreshToken
	}
	return nil
}

func init() {
	proto.RegisterType((*RefreshToken)(nil), "charonrpc.RefreshToken")
	proto.RegisterType((*RefreshTokenQuery)(nil), "charonrpc.RefreshTokenQuery")
	proto.RegisterType((*CreateRefreshTokenRequest)(nil), "charonrpc.CreateRefreshTokenRequest")
	proto.RegisterType((*CreateRefreshTokenResponse)(nil), "charonrpc.CreateRefreshTokenResponse")
	proto.RegisterType((*ListRefreshTokensRequest)(nil), "charonrpc.ListRefreshTokensRequest")
	proto.RegisterType((*ListRefreshTokensResponse)(nil), "charonrpc.ListRefreshTokensResponse")
	proto.RegisterType((*DisableRefreshTokenRequest)(nil), "charonrpc.DisableRefreshTokenRequest")
	proto.RegisterType((*DisableRefreshTokenResponse)(nil), "charonrpc.DisableRefreshTokenResponse")
}

func init() { proto.RegisterFile("charonrpc/refresh_token.proto", fileDescriptor_5540bd1101661962) }

var fileDescriptor_5540bd1101661962 = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x7d, 0xce, 0x77, 0x6e, 0xd2, 0xaa, 0x9d, 0x3e, 0xbd, 0xba, 0x7e, 0x20, 0x22, 0xf7, 0x43,
	0x11, 0x54, 0x4e, 0x95, 0x22, 0x10, 0x52, 0x85, 0xd4, 0xc0, 0xa6, 0x7c, 0x08, 0xe1, 0x16, 0x21,
	0xb5, 0x8b, 0xc8, 0x89, 0x27, 0xa9, 0xd5, 0xc4, 0xe3, 0xcc, 0x8c, 0x05, 0xee, 0x9f, 0xe1, 0xef,
	0xb0, 0x61, 0xc7, 0x0f, 0x42, 0xf6, 0xd8, 0xce, 0xb8, 0xd8, 0x0d, 0x0b, 0x56, 0xd1, 0xf8, 0x9e,
	0x73, 0xe6, 0xde, 0x7b, 0x4e, 0x06, 0x1e, 0x8e, 0xaf, 0x2d, 0x4a, 0x5c, 0xea, 0x8d, 0x7b, 0x14,
	0x4f, 0x28, 0x66, 0xd7, 0x43, 0x4e, 0x6e, 0xb0, 0x6b, 0x78, 0x94, 0x70, 0x82, 0x9a, 0x69, 0x59,
	0x7b, 0x34, 0x25, 0x64, 0x3a, 0xc3, 0xbd, 0xa8, 0x30, 0xf2, 0x27, 0x3d, 0xee, 0xcc, 0x31, 0xe3,
	0xd6, 0xdc, 0x13, 0x58, 0xed, 0xbf, 0xa5, 0xd4, 0x98, 0xcc, 0xe7, 0x24, 0xd6, 0xd0, 0xb6, 0x16,
	0x3c, 0xf0, 0x30, 0xeb, 0x89, 0x9f, 0xe4, 0xa3, 0x2b, 0x3e, 0xba, 0xd2, 0x47, 0xfd, 0x7b, 0x19,
	0xda, 0xa6, 0xe8, 0xe2, 0x22, 0x6c, 0x02, 0xfd, 0x0b, 0xd5, 0xa8, 0x1b, 0x55, 0xe9, 0x28, 0xdd,
	0xa6, 0x29, 0x0e, 0x68, 0x0f, 0xaa, 0x2e, 0xe1, 0x98, 0xa9, 0xa5, 0x8e, 0xd2, 0x6d, 0xf5, 0xd7,
	0x8d, 0x58, 0xe4, 0x9c, 0x53, 0xc7, 0x9d, 0x9a, 0xa2, 0x88, 0xb6, 0xa1, 0xee, 0x33, 0x4c, 0x87,
	0x8e, 0xad, 0x96, 0x3b, 0x4a, 0xb7, 0x6c, 0xd6, 0xc2, 0xe3, 0x99, 0x8d, 0x34, 0x68, 0xd8, 0x0e,
	0xb3, 0x46, 0x33, 0x6c, 0xab, 0x95, 0x8e, 0xd2, 0x6d, 0x98, 0xe9, 0x19, 0x3d, 0x87, 0x26, 0xfe,
	0xea, 0x39, 0x14, 0x0f, 0x2d, 0xae, 0x56, 0x23, 0x79, 0xcd, 0x10, 0x83, 0x1b, 0xc9, 0xe0, 0xc6,
	0x45, 0x32, 0xb8, 0xd9, 0x10, 0xe0, 0x53, 0x8e, 0x4e, 0xa0, 0x3d, 0xb3, 0x18, 0x1f, 0xfa, 0x0c,
	0xdb, 0x21, 0xb7, 0xb6, 0x92, 0x0b, 0x21, 0xfe, 0x13, 0xc3, 0xf6, 0x29, 0x47, 0x2f, 0x00, 0xc6,
	0x14, 0x5b, 0x5c, 0x70, 0xeb, 0x2b, 0xb9, 0xcd, 0x18, 0x7d, 0xca, 0xd1, 0xe1, 0x92, 0x3a, 0x0a,
	0xd4, 0x46, 0x44, 0x5d, 0x4b, 0x36, 0x72, 0xe6, 0xf2, 0x67, 0x4f, 0x53, 0xf4, 0x20, 0x08, 0x2f,
	0xf2, 0x3d, 0x3b, 0xb9, 0xa8, 0xb9, 0xfa, 0xa2, 0x18, 0x2d, 0x2e, 0x4a, 0xa8, 0xa3, 0x40, 0x85,
	0xdc, 0x8b, 0x62, 0xc0, 0x20, 0xd0, 0x7f, 0x96, 0x60, 0x53, 0xb6, 0xf2, 0xa3, 0x8f, 0x69, 0x80,
	0x0e, 0x96, 0x9e, 0x28, 0xb1, 0xc0, 0x42, 0x16, 0x48, 0x2c, 0xfa, 0xcd, 0xe1, 0x45, 0x9e, 0xc3,
	0x5d, 0xc9, 0xc8, 0x72, 0x04, 0x6c, 0x27, 0xfd, 0x0c, 0x08, 0x99, 0x49, 0xb6, 0x1a, 0xb2, 0xad,
	0x95, 0x08, 0xba, 0x99, 0x68, 0xe6, 0xb9, 0x79, 0x7c, 0xc7, 0xcd, 0x6a, 0x11, 0x45, 0x36, 0xf1,
	0x28, 0x63, 0x62, 0xad, 0x88, 0x22, 0x79, 0x77, 0x94, 0x71, 0xa3, 0x5e, 0xc8, 0x48, 0x4d, 0xd0,
	0x6f, 0x61, 0xe7, 0x55, 0x44, 0x97, 0x77, 0x6b, 0xe2, 0x85, 0x8f, 0x19, 0x5f, 0x6e, 0x4d, 0xb9,
	0xef, 0x7f, 0x91, 0x89, 0x78, 0xe9, 0xcf, 0x23, 0xae, 0x5f, 0x82, 0x96, 0x77, 0x37, 0xf3, 0x88,
	0xcb, 0x30, 0x3a, 0x81, 0xb5, 0xcc, 0x03, 0x12, 0x37, 0xb1, 0x6d, 0xa4, 0xaf, 0x82, 0x91, 0xe1,
	0xb5, 0xa9, 0x74, 0xd2, 0x7f, 0x28, 0xa0, 0xbe, 0x73, 0x18, 0x97, 0x21, 0x2c, 0x99, 0x6b, 0x1f,
	0x6a, 0x64, 0x32, 0x61, 0x98, 0xa7, 0xa1, 0xc9, 0xa4, 0x2e, 0x2e, 0xa2, 0x5d, 0xa8, 0xce, 0x9c,
	0xb9, 0x93, 0x0c, 0x75, 0x07, 0x25, 0x6a, 0xe8, 0x09, 0x34, 0x08, 0xb5, 0x31, 0x0d, 0x33, 0x5c,
	0xee, 0x94, 0xbb, 0xad, 0xfe, 0x86, 0xd4, 0xe1, 0x87, 0xb0, 0x64, 0xd6, 0x23, 0xc4, 0x20, 0x40,
	0x7d, 0xa8, 0x2e, 0xc2, 0xdc, 0xaa, 0xad, 0x48, 0xf1, 0x41, 0xc1, 0x2c, 0x51, 0xb6, 0x4d, 0x01,
	0x7d, 0x53, 0x69, 0x54, 0x36, 0x5a, 0xfa, 0x15, 0xec, 0xe4, 0x8c, 0x13, 0xaf, 0xea, 0x25, 0xac,
	0x67, 0x56, 0x15, 0x1a, 0x56, 0xbe, 0x6f, 0x57, 0x6b, 0xf2, 0xae, 0x98, 0xfe, 0x16, 0xb4, 0xd7,
	0x22, 0xd9, 0x79, 0x29, 0xc8, 0x7f, 0x33, 0xa5, 0xd7, 0xb0, 0x24, 0xbf, 0x86, 0xfa, 0x15, 0xfc,
	0x9f, 0x2b, 0xf6, 0x37, 0x6c, 0xed, 0x7f, 0x2b, 0xc1, 0x96, 0x5c, 0x7e, 0x6f, 0xb9, 0xd6, 0x14,
	0x53, 0xf4, 0x19, 0x6a, 0x22, 0x4a, 0x68, 0x4f, 0x12, 0x2a, 0x4c, 0xb6, 0xb6, 0xbf, 0x02, 0x25,
	0x9a, 0xd5, 0xff, 0x41, 0x97, 0x50, 0x8f, 0xa7, 0x41, 0x32, 0xa7, 0x78, 0x5d, 0xda, 0xc1, 0x2a,
	0x58, 0xaa, 0x7d, 0x0e, 0x95, 0xd0, 0x53, 0xb4, 0x2b, 0x31, 0x8a, 0x32, 0xab, 0xed, 0xdd, 0x0f,
	0x4a, 0x44, 0x07, 0x87, 0x97, 0x8f, 0xa7, 0x0e, 0xbf, 0xf6, 0x47, 0xc6, 0x98, 0xcc, 0x7b, 0x9e,
	0x43, 0x38, 0xbd, 0x21, 0x5f, 0xac, 0xd9, 0xf8, 0xd6, 0xbf, 0xe9, 0x09, 0x89, 0x5e, 0xaa, 0x34,
	0xaa, 0x45, 0x7f, 0xd0, 0xe3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xef, 0xea, 0x9c, 0x54, 0xb6,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RefreshTokenManagerClient is the client API for RefreshTokenManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RefreshTokenManagerClient interface {
	Create(ctx context.Context, in *CreateRefreshTokenRequest, opts ...grpc.CallOption) (*CreateRefreshTokenResponse, error)
	Disable(ctx context.Context, in *DisableRefreshTokenRequest, opts ...grpc.CallOption) (*DisableRefreshTokenResponse, error)
	List(ctx context.Context, in *ListRefreshTokensRequest, opts ...grpc.CallOption) (*ListRefreshTokensResponse, error)
}

type refreshTokenManagerClient struct {
	cc *grpc.ClientConn
}

func NewRefreshTokenManagerClient(cc *grpc.ClientConn) RefreshTokenManagerClient {
	return &refreshTokenManagerClient{cc}
}

func (c *refreshTokenManagerClient) Create(ctx context.Context, in *CreateRefreshTokenRequest, opts ...grpc.CallOption) (*CreateRefreshTokenResponse, error) {
	out := new(CreateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/charonrpc.RefreshTokenManager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refreshTokenManagerClient) Disable(ctx context.Context, in *DisableRefreshTokenRequest, opts ...grpc.CallOption) (*DisableRefreshTokenResponse, error) {
	out := new(DisableRefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/charonrpc.RefreshTokenManager/Disable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refreshTokenManagerClient) List(ctx context.Context, in *ListRefreshTokensRequest, opts ...grpc.CallOption) (*ListRefreshTokensResponse, error) {
	out := new(ListRefreshTokensResponse)
	err := c.cc.Invoke(ctx, "/charonrpc.RefreshTokenManager/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefreshTokenManagerServer is the server API for RefreshTokenManager service.
type RefreshTokenManagerServer interface {
	Create(context.Context, *CreateRefreshTokenRequest) (*CreateRefreshTokenResponse, error)
	Disable(context.Context, *DisableRefreshTokenRequest) (*DisableRefreshTokenResponse, error)
	List(context.Context, *ListRefreshTokensRequest) (*ListRefreshTokensResponse, error)
}

func RegisterRefreshTokenManagerServer(s *grpc.Server, srv RefreshTokenManagerServer) {
	s.RegisterService(&_RefreshTokenManager_serviceDesc, srv)
}

func _RefreshTokenManager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefreshTokenManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charonrpc.RefreshTokenManager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefreshTokenManagerServer).Create(ctx, req.(*CreateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefreshTokenManager_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefreshTokenManagerServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charonrpc.RefreshTokenManager/Disable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefreshTokenManagerServer).Disable(ctx, req.(*DisableRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefreshTokenManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefreshTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefreshTokenManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charonrpc.RefreshTokenManager/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefreshTokenManagerServer).List(ctx, req.(*ListRefreshTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RefreshTokenManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "charonrpc.RefreshTokenManager",
	HandlerType: (*RefreshTokenManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RefreshTokenManager_Create_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _RefreshTokenManager_Disable_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RefreshTokenManager_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "charonrpc/refresh_token.proto",
}
