// Code generated by protoc-gen-go.
// source: charon.proto
// DO NOT EDIT!

/*
Package charon is a generated protocol buffer package.

It is generated from these files:
	charon.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	IsAuthenticatedRequest
	IsAuthenticatedResponse
	IsGrantedRequest
	IsGrantedResponse
	BelongsToRequest
	BelongsToResponse
	SubjectRequest
	SubjectResponse
	User
	CreateUserRequest
	CreateUserResponse
	GetUserRequest
	GetUserResponse
	ListUsersRequest
	ListUsersResponse
	DeleteUserRequest
	DeleteUserResponse
	ModifyUserRequest
	ModifyUserResponse
	ListUserPermissionsRequest
	ListUserPermissionsResponse
	SetUserPermissionsRequest
	SetUserPermissionsResponse
	ListUserGroupsRequest
	ListUserGroupsResponse
	SetUserGroupsRequest
	SetUserGroupsResponse
	RegisterPermissionsRequest
	RegisterPermissionsResponse
	ListPermissionsRequest
	ListPermissionsResponse
	GetPermissionRequest
	GetPermissionResponse
	Group
	CreateGroupRequest
	CreateGroupResponse
	GetGroupRequest
	GetGroupResponse
	ListGroupsRequest
	ListGroupsResponse
	DeleteGroupRequest
	DeleteGroupResponse
	ModifyGroupRequest
	ModifyGroupResponse
	SetGroupPermissionsRequest
	SetGroupPermissionsResponse
	ListGroupPermissionsRequest
	ListGroupPermissionsResponse
*/
package charon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import mnemosyne "github.com/piotrkowalczuk/mnemosyne"
import qtypes "github.com/piotrkowalczuk/qtypes"
import ntypes "github.com/piotrkowalczuk/ntypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginResponse struct {
	AccessToken *mnemosyne.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetAccessToken() *mnemosyne.AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

type LogoutRequest struct {
	AccessToken *mnemosyne.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogoutRequest) GetAccessToken() *mnemosyne.AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type IsAuthenticatedRequest struct {
	AccessToken *mnemosyne.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *IsAuthenticatedRequest) Reset()                    { *m = IsAuthenticatedRequest{} }
func (m *IsAuthenticatedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsAuthenticatedRequest) ProtoMessage()               {}
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IsAuthenticatedRequest) GetAccessToken() *mnemosyne.AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

type IsAuthenticatedResponse struct {
	Authenticated bool `protobuf:"varint,1,opt,name=authenticated" json:"authenticated,omitempty"`
}

func (m *IsAuthenticatedResponse) Reset()                    { *m = IsAuthenticatedResponse{} }
func (m *IsAuthenticatedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsAuthenticatedResponse) ProtoMessage()               {}
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type IsGrantedRequest struct {
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Permission string `protobuf:"bytes,2,opt,name=permission" json:"permission,omitempty"`
}

func (m *IsGrantedRequest) Reset()                    { *m = IsGrantedRequest{} }
func (m *IsGrantedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsGrantedRequest) ProtoMessage()               {}
func (*IsGrantedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type IsGrantedResponse struct {
	Granted bool `protobuf:"varint,1,opt,name=granted" json:"granted,omitempty"`
}

func (m *IsGrantedResponse) Reset()                    { *m = IsGrantedResponse{} }
func (m *IsGrantedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsGrantedResponse) ProtoMessage()               {}
func (*IsGrantedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BelongsToRequest struct {
	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
}

func (m *BelongsToRequest) Reset()                    { *m = BelongsToRequest{} }
func (m *BelongsToRequest) String() string            { return proto.CompactTextString(m) }
func (*BelongsToRequest) ProtoMessage()               {}
func (*BelongsToRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type BelongsToResponse struct {
	Belongs bool `protobuf:"varint,1,opt,name=belongs" json:"belongs,omitempty"`
}

func (m *BelongsToResponse) Reset()                    { *m = BelongsToResponse{} }
func (m *BelongsToResponse) String() string            { return proto.CompactTextString(m) }
func (*BelongsToResponse) ProtoMessage()               {}
func (*BelongsToResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SubjectRequest struct {
	AccessToken *mnemosyne.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *SubjectRequest) Reset()                    { *m = SubjectRequest{} }
func (m *SubjectRequest) String() string            { return proto.CompactTextString(m) }
func (*SubjectRequest) ProtoMessage()               {}
func (*SubjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SubjectRequest) GetAccessToken() *mnemosyne.AccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

type SubjectResponse struct {
	Id          int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username    string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName   string   `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName    string   `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Permissions []string `protobuf:"bytes,5,rep,name=permissions" json:"permissions,omitempty"`
	IsSuperuser bool     `protobuf:"varint,6,opt,name=is_superuser,json=isSuperuser" json:"is_superuser,omitempty"`
	IsActive    bool     `protobuf:"varint,7,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	IsStuff     bool     `protobuf:"varint,8,opt,name=is_stuff,json=isStuff" json:"is_stuff,omitempty"`
	IsConfirmed bool     `protobuf:"varint,9,opt,name=is_confirmed,json=isConfirmed" json:"is_confirmed,omitempty"`
}

func (m *SubjectResponse) Reset()                    { *m = SubjectResponse{} }
func (m *SubjectResponse) String() string            { return proto.CompactTextString(m) }
func (*SubjectResponse) ProtoMessage()               {}
func (*SubjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type User struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username    string                     `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName   string                     `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName    string                     `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	IsSuperuser bool                       `protobuf:"varint,5,opt,name=is_superuser,json=isSuperuser" json:"is_superuser,omitempty"`
	IsActive    bool                       `protobuf:"varint,6,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	IsStaff     bool                       `protobuf:"varint,7,opt,name=is_staff,json=isStaff" json:"is_staff,omitempty"`
	IsConfirmed bool                       `protobuf:"varint,8,opt,name=is_confirmed,json=isConfirmed" json:"is_confirmed,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	CreatedBy   *ntypes.Int64              `protobuf:"bytes,10,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	UpdatedAt   *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	UpdatedBy   *ntypes.Int64              `protobuf:"bytes,12,opt,name=updated_by,json=updatedBy" json:"updated_by,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *User) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetCreatedBy() *ntypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *User) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetUpdatedBy() *ntypes.Int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

type CreateUserRequest struct {
	Username       string       `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PlainPassword  string       `protobuf:"bytes,2,opt,name=plain_password,json=plainPassword" json:"plain_password,omitempty"`
	SecurePassword []byte       `protobuf:"bytes,3,opt,name=secure_password,json=securePassword,proto3" json:"secure_password,omitempty"`
	FirstName      string       `protobuf:"bytes,4,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName       string       `protobuf:"bytes,5,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	IsSuperuser    *ntypes.Bool `protobuf:"bytes,6,opt,name=is_superuser,json=isSuperuser" json:"is_superuser,omitempty"`
	IsActive       *ntypes.Bool `protobuf:"bytes,7,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	IsStaff        *ntypes.Bool `protobuf:"bytes,8,opt,name=is_staff,json=isStaff" json:"is_staff,omitempty"`
	IsConfirmed    *ntypes.Bool `protobuf:"bytes,9,opt,name=is_confirmed,json=isConfirmed" json:"is_confirmed,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CreateUserRequest) GetIsSuperuser() *ntypes.Bool {
	if m != nil {
		return m.IsSuperuser
	}
	return nil
}

func (m *CreateUserRequest) GetIsActive() *ntypes.Bool {
	if m != nil {
		return m.IsActive
	}
	return nil
}

func (m *CreateUserRequest) GetIsStaff() *ntypes.Bool {
	if m != nil {
		return m.IsStaff
	}
	return nil
}

func (m *CreateUserRequest) GetIsConfirmed() *ntypes.Bool {
	if m != nil {
		return m.IsConfirmed
	}
	return nil
}

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUsersRequest struct {
	IsSuperuser *ntypes.Bool    `protobuf:"bytes,1,opt,name=is_superuser,json=isSuperuser" json:"is_superuser,omitempty"`
	IsStaff     *ntypes.Bool    `protobuf:"bytes,2,opt,name=is_staff,json=isStaff" json:"is_staff,omitempty"`
	CreatedBy   *qtypes.Int64   `protobuf:"bytes,3,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	Offset      *ntypes.Int64   `protobuf:"bytes,100,opt,name=offset" json:"offset,omitempty"`
	Limit       *ntypes.Int64   `protobuf:"bytes,101,opt,name=limit" json:"limit,omitempty"`
	Sort        map[string]bool `protobuf:"bytes,102,rep,name=sort" json:"sort,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ListUsersRequest) GetIsSuperuser() *ntypes.Bool {
	if m != nil {
		return m.IsSuperuser
	}
	return nil
}

func (m *ListUsersRequest) GetIsStaff() *ntypes.Bool {
	if m != nil {
		return m.IsStaff
	}
	return nil
}

func (m *ListUsersRequest) GetCreatedBy() *qtypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *ListUsersRequest) GetOffset() *ntypes.Int64 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ListUsersRequest) GetLimit() *ntypes.Int64 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListUsersRequest) GetSort() map[string]bool {
	if m != nil {
		return m.Sort
	}
	return nil
}

type ListUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersResponse) Reset()                    { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()               {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type DeleteUserResponse struct {
	Affected int64 `protobuf:"varint,1,opt,name=affected" json:"affected,omitempty"`
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ModifyUserRequest struct {
	Id             int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username       *ntypes.String `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	PlainPassword  *ntypes.String `protobuf:"bytes,3,opt,name=plain_password,json=plainPassword" json:"plain_password,omitempty"`
	SecurePassword []byte         `protobuf:"bytes,4,opt,name=secure_password,json=securePassword,proto3" json:"secure_password,omitempty"`
	FirstName      *ntypes.String `protobuf:"bytes,5,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName       *ntypes.String `protobuf:"bytes,6,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	IsSuperuser    *ntypes.Bool   `protobuf:"bytes,7,opt,name=is_superuser,json=isSuperuser" json:"is_superuser,omitempty"`
	IsActive       *ntypes.Bool   `protobuf:"bytes,8,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	IsStaff        *ntypes.Bool   `protobuf:"bytes,9,opt,name=is_staff,json=isStaff" json:"is_staff,omitempty"`
	IsConfirmed    *ntypes.Bool   `protobuf:"bytes,10,opt,name=is_confirmed,json=isConfirmed" json:"is_confirmed,omitempty"`
}

func (m *ModifyUserRequest) Reset()                    { *m = ModifyUserRequest{} }
func (m *ModifyUserRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyUserRequest) ProtoMessage()               {}
func (*ModifyUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ModifyUserRequest) GetUsername() *ntypes.String {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ModifyUserRequest) GetPlainPassword() *ntypes.String {
	if m != nil {
		return m.PlainPassword
	}
	return nil
}

func (m *ModifyUserRequest) GetFirstName() *ntypes.String {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *ModifyUserRequest) GetLastName() *ntypes.String {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *ModifyUserRequest) GetIsSuperuser() *ntypes.Bool {
	if m != nil {
		return m.IsSuperuser
	}
	return nil
}

func (m *ModifyUserRequest) GetIsActive() *ntypes.Bool {
	if m != nil {
		return m.IsActive
	}
	return nil
}

func (m *ModifyUserRequest) GetIsStaff() *ntypes.Bool {
	if m != nil {
		return m.IsStaff
	}
	return nil
}

func (m *ModifyUserRequest) GetIsConfirmed() *ntypes.Bool {
	if m != nil {
		return m.IsConfirmed
	}
	return nil
}

type ModifyUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ModifyUserResponse) Reset()                    { *m = ModifyUserResponse{} }
func (m *ModifyUserResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyUserResponse) ProtoMessage()               {}
func (*ModifyUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ModifyUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUserPermissionsRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListUserPermissionsRequest) Reset()                    { *m = ListUserPermissionsRequest{} }
func (m *ListUserPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUserPermissionsRequest) ProtoMessage()               {}
func (*ListUserPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type ListUserPermissionsResponse struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *ListUserPermissionsResponse) Reset()                    { *m = ListUserPermissionsResponse{} }
func (m *ListUserPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUserPermissionsResponse) ProtoMessage()               {}
func (*ListUserPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type SetUserPermissionsRequest struct {
	UserId      int64    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *SetUserPermissionsRequest) Reset()                    { *m = SetUserPermissionsRequest{} }
func (m *SetUserPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserPermissionsRequest) ProtoMessage()               {}
func (*SetUserPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type SetUserPermissionsResponse struct {
	Created   int64 `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Removed   int64 `protobuf:"varint,2,opt,name=removed" json:"removed,omitempty"`
	Untouched int64 `protobuf:"varint,3,opt,name=untouched" json:"untouched,omitempty"`
}

func (m *SetUserPermissionsResponse) Reset()                    { *m = SetUserPermissionsResponse{} }
func (m *SetUserPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserPermissionsResponse) ProtoMessage()               {}
func (*SetUserPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type ListUserGroupsRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListUserGroupsRequest) Reset()                    { *m = ListUserGroupsRequest{} }
func (m *ListUserGroupsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUserGroupsRequest) ProtoMessage()               {}
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type ListUserGroupsResponse struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *ListUserGroupsResponse) Reset()                    { *m = ListUserGroupsResponse{} }
func (m *ListUserGroupsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUserGroupsResponse) ProtoMessage()               {}
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ListUserGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type SetUserGroupsRequest struct {
	UserId int64   `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Groups []int64 `protobuf:"varint,2,rep,name=groups" json:"groups,omitempty"`
}

func (m *SetUserGroupsRequest) Reset()                    { *m = SetUserGroupsRequest{} }
func (m *SetUserGroupsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserGroupsRequest) ProtoMessage()               {}
func (*SetUserGroupsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type SetUserGroupsResponse struct {
	Created   int64 `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Removed   int64 `protobuf:"varint,2,opt,name=removed" json:"removed,omitempty"`
	Untouched int64 `protobuf:"varint,3,opt,name=untouched" json:"untouched,omitempty"`
}

func (m *SetUserGroupsResponse) Reset()                    { *m = SetUserGroupsResponse{} }
func (m *SetUserGroupsResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserGroupsResponse) ProtoMessage()               {}
func (*SetUserGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type RegisterPermissionsRequest struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *RegisterPermissionsRequest) Reset()                    { *m = RegisterPermissionsRequest{} }
func (m *RegisterPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterPermissionsRequest) ProtoMessage()               {}
func (*RegisterPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type RegisterPermissionsResponse struct {
	Created   int64 `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Removed   int64 `protobuf:"varint,2,opt,name=removed" json:"removed,omitempty"`
	Untouched int64 `protobuf:"varint,3,opt,name=untouched" json:"untouched,omitempty"`
}

func (m *RegisterPermissionsResponse) Reset()                    { *m = RegisterPermissionsResponse{} }
func (m *RegisterPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterPermissionsResponse) ProtoMessage()               {}
func (*RegisterPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type ListPermissionsRequest struct {
	Subsystem *qtypes.String    `protobuf:"bytes,1,opt,name=subsystem" json:"subsystem,omitempty"`
	Module    *qtypes.String    `protobuf:"bytes,2,opt,name=module" json:"module,omitempty"`
	Action    *qtypes.String    `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	CreatedAt *qtypes.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	CreatedBy *qtypes.Int64     `protobuf:"bytes,5,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	Offset    *ntypes.Int64     `protobuf:"bytes,100,opt,name=offset" json:"offset,omitempty"`
	Limit     *ntypes.Int64     `protobuf:"bytes,101,opt,name=limit" json:"limit,omitempty"`
	Sort      map[string]bool   `protobuf:"bytes,102,rep,name=sort" json:"sort,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *ListPermissionsRequest) Reset()                    { *m = ListPermissionsRequest{} }
func (m *ListPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPermissionsRequest) ProtoMessage()               {}
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *ListPermissionsRequest) GetSubsystem() *qtypes.String {
	if m != nil {
		return m.Subsystem
	}
	return nil
}

func (m *ListPermissionsRequest) GetModule() *qtypes.String {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *ListPermissionsRequest) GetAction() *qtypes.String {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ListPermissionsRequest) GetCreatedAt() *qtypes.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListPermissionsRequest) GetCreatedBy() *qtypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *ListPermissionsRequest) GetOffset() *ntypes.Int64 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ListPermissionsRequest) GetLimit() *ntypes.Int64 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListPermissionsRequest) GetSort() map[string]bool {
	if m != nil {
		return m.Sort
	}
	return nil
}

type ListPermissionsResponse struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *ListPermissionsResponse) Reset()                    { *m = ListPermissionsResponse{} }
func (m *ListPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPermissionsResponse) ProtoMessage()               {}
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type GetPermissionRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPermissionRequest) Reset()                    { *m = GetPermissionRequest{} }
func (m *GetPermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionRequest) ProtoMessage()               {}
func (*GetPermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type GetPermissionResponse struct {
	Permission string `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
}

func (m *GetPermissionResponse) Reset()                    { *m = GetPermissionResponse{} }
func (m *GetPermissionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionResponse) ProtoMessage()               {}
func (*GetPermissionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type Group struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	CreatedBy   *ntypes.Int64              `protobuf:"bytes,5,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	UpdatedAt   *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	UpdatedBy   *ntypes.Int64              `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy" json:"updated_by,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *Group) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Group) GetCreatedBy() *ntypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *Group) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Group) GetUpdatedBy() *ntypes.Int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

type CreateGroupRequest struct {
	Name        string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description *ntypes.String `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CreateGroupRequest) Reset()                    { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()               {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *CreateGroupRequest) GetDescription() *ntypes.String {
	if m != nil {
		return m.Description
	}
	return nil
}

type CreateGroupResponse struct {
	Group *Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *CreateGroupResponse) Reset()                    { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()               {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *CreateGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GetGroupRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetGroupRequest) Reset()                    { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()               {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type GetGroupResponse struct {
	Group *Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *GetGroupResponse) Reset()                    { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()               {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *GetGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListGroupsRequest struct {
	Offset *ntypes.Int64 `protobuf:"bytes,100,opt,name=offset" json:"offset,omitempty"`
	Limit  *ntypes.Int64 `protobuf:"bytes,101,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListGroupsRequest) Reset()                    { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()               {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *ListGroupsRequest) GetOffset() *ntypes.Int64 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ListGroupsRequest) GetLimit() *ntypes.Int64 {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ListGroupsResponse struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *ListGroupsResponse) Reset()                    { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()               {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type DeleteGroupRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteGroupRequest) Reset()                    { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()               {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type DeleteGroupResponse struct {
	Affected int64 `protobuf:"varint,1,opt,name=affected" json:"affected,omitempty"`
}

func (m *DeleteGroupResponse) Reset()                    { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteGroupResponse) ProtoMessage()               {}
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

type ModifyGroupRequest struct {
	Id          int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        *ntypes.String `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description *ntypes.String `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ModifyGroupRequest) Reset()                    { *m = ModifyGroupRequest{} }
func (m *ModifyGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyGroupRequest) ProtoMessage()               {}
func (*ModifyGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *ModifyGroupRequest) GetName() *ntypes.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyGroupRequest) GetDescription() *ntypes.String {
	if m != nil {
		return m.Description
	}
	return nil
}

type ModifyGroupResponse struct {
	Group *Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
}

func (m *ModifyGroupResponse) Reset()                    { *m = ModifyGroupResponse{} }
func (m *ModifyGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyGroupResponse) ProtoMessage()               {}
func (*ModifyGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *ModifyGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type SetGroupPermissionsRequest struct {
	GroupId     int64    `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *SetGroupPermissionsRequest) Reset()                    { *m = SetGroupPermissionsRequest{} }
func (m *SetGroupPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetGroupPermissionsRequest) ProtoMessage()               {}
func (*SetGroupPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

type SetGroupPermissionsResponse struct {
	Created   int64 `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Removed   int64 `protobuf:"varint,2,opt,name=removed" json:"removed,omitempty"`
	Untouched int64 `protobuf:"varint,3,opt,name=untouched" json:"untouched,omitempty"`
}

func (m *SetGroupPermissionsResponse) Reset()                    { *m = SetGroupPermissionsResponse{} }
func (m *SetGroupPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*SetGroupPermissionsResponse) ProtoMessage()               {}
func (*SetGroupPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

type ListGroupPermissionsRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListGroupPermissionsRequest) Reset()                    { *m = ListGroupPermissionsRequest{} }
func (m *ListGroupPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGroupPermissionsRequest) ProtoMessage()               {}
func (*ListGroupPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

type ListGroupPermissionsResponse struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *ListGroupPermissionsResponse) Reset()                    { *m = ListGroupPermissionsResponse{} }
func (m *ListGroupPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGroupPermissionsResponse) ProtoMessage()               {}
func (*ListGroupPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func init() {
	proto.RegisterType((*LoginRequest)(nil), "charon.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "charon.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "charon.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "charon.LogoutResponse")
	proto.RegisterType((*IsAuthenticatedRequest)(nil), "charon.IsAuthenticatedRequest")
	proto.RegisterType((*IsAuthenticatedResponse)(nil), "charon.IsAuthenticatedResponse")
	proto.RegisterType((*IsGrantedRequest)(nil), "charon.IsGrantedRequest")
	proto.RegisterType((*IsGrantedResponse)(nil), "charon.IsGrantedResponse")
	proto.RegisterType((*BelongsToRequest)(nil), "charon.BelongsToRequest")
	proto.RegisterType((*BelongsToResponse)(nil), "charon.BelongsToResponse")
	proto.RegisterType((*SubjectRequest)(nil), "charon.SubjectRequest")
	proto.RegisterType((*SubjectResponse)(nil), "charon.SubjectResponse")
	proto.RegisterType((*User)(nil), "charon.User")
	proto.RegisterType((*CreateUserRequest)(nil), "charon.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "charon.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "charon.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "charon.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "charon.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "charon.ListUsersResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "charon.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "charon.DeleteUserResponse")
	proto.RegisterType((*ModifyUserRequest)(nil), "charon.ModifyUserRequest")
	proto.RegisterType((*ModifyUserResponse)(nil), "charon.ModifyUserResponse")
	proto.RegisterType((*ListUserPermissionsRequest)(nil), "charon.ListUserPermissionsRequest")
	proto.RegisterType((*ListUserPermissionsResponse)(nil), "charon.ListUserPermissionsResponse")
	proto.RegisterType((*SetUserPermissionsRequest)(nil), "charon.SetUserPermissionsRequest")
	proto.RegisterType((*SetUserPermissionsResponse)(nil), "charon.SetUserPermissionsResponse")
	proto.RegisterType((*ListUserGroupsRequest)(nil), "charon.ListUserGroupsRequest")
	proto.RegisterType((*ListUserGroupsResponse)(nil), "charon.ListUserGroupsResponse")
	proto.RegisterType((*SetUserGroupsRequest)(nil), "charon.SetUserGroupsRequest")
	proto.RegisterType((*SetUserGroupsResponse)(nil), "charon.SetUserGroupsResponse")
	proto.RegisterType((*RegisterPermissionsRequest)(nil), "charon.RegisterPermissionsRequest")
	proto.RegisterType((*RegisterPermissionsResponse)(nil), "charon.RegisterPermissionsResponse")
	proto.RegisterType((*ListPermissionsRequest)(nil), "charon.ListPermissionsRequest")
	proto.RegisterType((*ListPermissionsResponse)(nil), "charon.ListPermissionsResponse")
	proto.RegisterType((*GetPermissionRequest)(nil), "charon.GetPermissionRequest")
	proto.RegisterType((*GetPermissionResponse)(nil), "charon.GetPermissionResponse")
	proto.RegisterType((*Group)(nil), "charon.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "charon.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "charon.CreateGroupResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "charon.GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "charon.GetGroupResponse")
	proto.RegisterType((*ListGroupsRequest)(nil), "charon.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "charon.ListGroupsResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "charon.DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupResponse)(nil), "charon.DeleteGroupResponse")
	proto.RegisterType((*ModifyGroupRequest)(nil), "charon.ModifyGroupRequest")
	proto.RegisterType((*ModifyGroupResponse)(nil), "charon.ModifyGroupResponse")
	proto.RegisterType((*SetGroupPermissionsRequest)(nil), "charon.SetGroupPermissionsRequest")
	proto.RegisterType((*SetGroupPermissionsResponse)(nil), "charon.SetGroupPermissionsResponse")
	proto.RegisterType((*ListGroupPermissionsRequest)(nil), "charon.ListGroupPermissionsRequest")
	proto.RegisterType((*ListGroupPermissionsResponse)(nil), "charon.ListGroupPermissionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for RPC service

type RPCClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	IsAuthenticated(ctx context.Context, in *IsAuthenticatedRequest, opts ...grpc.CallOption) (*IsAuthenticatedResponse, error)
	Subject(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	IsGranted(ctx context.Context, in *IsGrantedRequest, opts ...grpc.CallOption) (*IsGrantedResponse, error)
	BelongsTo(ctx context.Context, in *BelongsToRequest, opts ...grpc.CallOption) (*BelongsToResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	ModifyUser(ctx context.Context, in *ModifyUserRequest, opts ...grpc.CallOption) (*ModifyUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ListUserPermissions(ctx context.Context, in *ListUserPermissionsRequest, opts ...grpc.CallOption) (*ListUserPermissionsResponse, error)
	SetUserPermissions(ctx context.Context, in *SetUserPermissionsRequest, opts ...grpc.CallOption) (*SetUserPermissionsResponse, error)
	ListUserGroups(ctx context.Context, in *ListUserGroupsRequest, opts ...grpc.CallOption) (*ListUserGroupsResponse, error)
	SetUserGroups(ctx context.Context, in *SetUserGroupsRequest, opts ...grpc.CallOption) (*SetUserGroupsResponse, error)
	RegisterPermissions(ctx context.Context, in *RegisterPermissionsRequest, opts ...grpc.CallOption) (*RegisterPermissionsResponse, error)
	ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*GetPermissionResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	ModifyGroup(ctx context.Context, in *ModifyGroupRequest, opts ...grpc.CallOption) (*ModifyGroupResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	ListGroupPermissions(ctx context.Context, in *ListGroupPermissionsRequest, opts ...grpc.CallOption) (*ListGroupPermissionsResponse, error)
	SetGroupPermissions(ctx context.Context, in *SetGroupPermissionsRequest, opts ...grpc.CallOption) (*SetGroupPermissionsResponse, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) IsAuthenticated(ctx context.Context, in *IsAuthenticatedRequest, opts ...grpc.CallOption) (*IsAuthenticatedResponse, error) {
	out := new(IsAuthenticatedResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/IsAuthenticated", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Subject(ctx context.Context, in *SubjectRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	out := new(SubjectResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/Subject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) IsGranted(ctx context.Context, in *IsGrantedRequest, opts ...grpc.CallOption) (*IsGrantedResponse, error) {
	out := new(IsGrantedResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/IsGranted", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) BelongsTo(ctx context.Context, in *BelongsToRequest, opts ...grpc.CallOption) (*BelongsToResponse, error) {
	out := new(BelongsToResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/BelongsTo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ModifyUser(ctx context.Context, in *ModifyUserRequest, opts ...grpc.CallOption) (*ModifyUserResponse, error) {
	out := new(ModifyUserResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ModifyUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListUserPermissions(ctx context.Context, in *ListUserPermissionsRequest, opts ...grpc.CallOption) (*ListUserPermissionsResponse, error) {
	out := new(ListUserPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListUserPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) SetUserPermissions(ctx context.Context, in *SetUserPermissionsRequest, opts ...grpc.CallOption) (*SetUserPermissionsResponse, error) {
	out := new(SetUserPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/SetUserPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListUserGroups(ctx context.Context, in *ListUserGroupsRequest, opts ...grpc.CallOption) (*ListUserGroupsResponse, error) {
	out := new(ListUserGroupsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListUserGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) SetUserGroups(ctx context.Context, in *SetUserGroupsRequest, opts ...grpc.CallOption) (*SetUserGroupsResponse, error) {
	out := new(SetUserGroupsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/SetUserGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) RegisterPermissions(ctx context.Context, in *RegisterPermissionsRequest, opts ...grpc.CallOption) (*RegisterPermissionsResponse, error) {
	out := new(RegisterPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/RegisterPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	out := new(ListPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*GetPermissionResponse, error) {
	out := new(GetPermissionResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/GetPermission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/CreateGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ModifyGroup(ctx context.Context, in *ModifyGroupRequest, opts ...grpc.CallOption) (*ModifyGroupResponse, error) {
	out := new(ModifyGroupResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ModifyGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	out := new(GetGroupResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/GetGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	out := new(DeleteGroupResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/DeleteGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ListGroupPermissions(ctx context.Context, in *ListGroupPermissionsRequest, opts ...grpc.CallOption) (*ListGroupPermissionsResponse, error) {
	out := new(ListGroupPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/ListGroupPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) SetGroupPermissions(ctx context.Context, in *SetGroupPermissionsRequest, opts ...grpc.CallOption) (*SetGroupPermissionsResponse, error) {
	out := new(SetGroupPermissionsResponse)
	err := grpc.Invoke(ctx, "/charon.RPC/SetGroupPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPC service

type RPCServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	IsAuthenticated(context.Context, *IsAuthenticatedRequest) (*IsAuthenticatedResponse, error)
	Subject(context.Context, *SubjectRequest) (*SubjectResponse, error)
	IsGranted(context.Context, *IsGrantedRequest) (*IsGrantedResponse, error)
	BelongsTo(context.Context, *BelongsToRequest) (*BelongsToResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ModifyUser(context.Context, *ModifyUserRequest) (*ModifyUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUserPermissions(context.Context, *ListUserPermissionsRequest) (*ListUserPermissionsResponse, error)
	SetUserPermissions(context.Context, *SetUserPermissionsRequest) (*SetUserPermissionsResponse, error)
	ListUserGroups(context.Context, *ListUserGroupsRequest) (*ListUserGroupsResponse, error)
	SetUserGroups(context.Context, *SetUserGroupsRequest) (*SetUserGroupsResponse, error)
	RegisterPermissions(context.Context, *RegisterPermissionsRequest) (*RegisterPermissionsResponse, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	GetPermission(context.Context, *GetPermissionRequest) (*GetPermissionResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	ModifyGroup(context.Context, *ModifyGroupRequest) (*ModifyGroupResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	ListGroupPermissions(context.Context, *ListGroupPermissionsRequest) (*ListGroupPermissionsResponse, error)
	SetGroupPermissions(context.Context, *SetGroupPermissionsRequest) (*SetGroupPermissionsResponse, error)
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_IsAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthenticatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).IsAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/IsAuthenticated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).IsAuthenticated(ctx, req.(*IsAuthenticatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Subject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Subject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/Subject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Subject(ctx, req.(*SubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_IsGranted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsGrantedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).IsGranted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/IsGranted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).IsGranted(ctx, req.(*IsGrantedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_BelongsTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BelongsToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).BelongsTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/BelongsTo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).BelongsTo(ctx, req.(*BelongsToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ModifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ModifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ModifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ModifyUser(ctx, req.(*ModifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListUserPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListUserPermissions(ctx, req.(*ListUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_SetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).SetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/SetUserPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).SetUserPermissions(ctx, req.(*SetUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListUserGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListUserGroups(ctx, req.(*ListUserGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_SetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).SetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/SetUserGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).SetUserGroups(ctx, req.(*SetUserGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_RegisterPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).RegisterPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/RegisterPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).RegisterPermissions(ctx, req.(*RegisterPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListPermissions(ctx, req.(*ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/GetPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).GetPermission(ctx, req.(*GetPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ModifyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ModifyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ModifyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ModifyGroup(ctx, req.(*ModifyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ListGroupPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListGroupPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/ListGroupPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListGroupPermissions(ctx, req.(*ListGroupPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_SetGroupPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).SetGroupPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.RPC/SetGroupPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).SetGroupPermissions(ctx, req.(*SetGroupPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "charon.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _RPC_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _RPC_Logout_Handler,
		},
		{
			MethodName: "IsAuthenticated",
			Handler:    _RPC_IsAuthenticated_Handler,
		},
		{
			MethodName: "Subject",
			Handler:    _RPC_Subject_Handler,
		},
		{
			MethodName: "IsGranted",
			Handler:    _RPC_IsGranted_Handler,
		},
		{
			MethodName: "BelongsTo",
			Handler:    _RPC_BelongsTo_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _RPC_CreateUser_Handler,
		},
		{
			MethodName: "ModifyUser",
			Handler:    _RPC_ModifyUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _RPC_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _RPC_ListUsers_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _RPC_DeleteUser_Handler,
		},
		{
			MethodName: "ListUserPermissions",
			Handler:    _RPC_ListUserPermissions_Handler,
		},
		{
			MethodName: "SetUserPermissions",
			Handler:    _RPC_SetUserPermissions_Handler,
		},
		{
			MethodName: "ListUserGroups",
			Handler:    _RPC_ListUserGroups_Handler,
		},
		{
			MethodName: "SetUserGroups",
			Handler:    _RPC_SetUserGroups_Handler,
		},
		{
			MethodName: "RegisterPermissions",
			Handler:    _RPC_RegisterPermissions_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _RPC_ListPermissions_Handler,
		},
		{
			MethodName: "GetPermission",
			Handler:    _RPC_GetPermission_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _RPC_CreateGroup_Handler,
		},
		{
			MethodName: "ModifyGroup",
			Handler:    _RPC_ModifyGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _RPC_GetGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _RPC_ListGroups_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _RPC_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroupPermissions",
			Handler:    _RPC_ListGroupPermissions_Handler,
		},
		{
			MethodName: "SetGroupPermissions",
			Handler:    _RPC_SetGroupPermissions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 1889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0xfd, 0x72, 0x13, 0x47,
	0x12, 0x3f, 0x7d, 0x4b, 0x2d, 0x5b, 0xb6, 0x07, 0x7f, 0x88, 0x35, 0xf8, 0xcc, 0x9a, 0xaf, 0xbb,
	0xc3, 0x36, 0x67, 0xee, 0xe0, 0x0e, 0xa8, 0x10, 0x9b, 0x10, 0xc7, 0x84, 0x50, 0x44, 0x26, 0xa9,
	0x4a, 0xaa, 0x52, 0xce, 0x5a, 0x1a, 0xc9, 0x1b, 0x4b, 0xbb, 0x62, 0x3f, 0xa0, 0xc4, 0xdf, 0x79,
	0x89, 0xfc, 0x95, 0x37, 0x49, 0x2a, 0x0f, 0x92, 0x87, 0xc8, 0x1b, 0x64, 0x76, 0x76, 0x66, 0x67,
	0x76, 0x77, 0x56, 0x92, 0x89, 0xe1, 0x2f, 0x69, 0xa7, 0x7b, 0x7e, 0x3d, 0xdd, 0xd3, 0xdd, 0xd3,
	0xdd, 0x30, 0xd3, 0x3e, 0x31, 0x1c, 0xdb, 0xda, 0x1a, 0x3a, 0xb6, 0x67, 0xa3, 0x72, 0xf8, 0xa5,
	0x3d, 0xe8, 0x99, 0xde, 0x89, 0x7f, 0xbc, 0xd5, 0xb6, 0x07, 0xdb, 0x3d, 0xbb, 0x6f, 0x58, 0xbd,
	0x6d, 0xca, 0x70, 0xec, 0x77, 0xb7, 0x87, 0xde, 0x68, 0x88, 0xdd, 0x6d, 0xcf, 0x1c, 0x60, 0xd7,
	0x33, 0x06, 0x43, 0xf1, 0x2f, 0x04, 0xd1, 0xee, 0x48, 0x9b, 0x87, 0xa6, 0xed, 0x39, 0xa7, 0xf6,
	0x1b, 0xa3, 0xdf, 0x7e, 0xeb, 0x9f, 0x6e, 0x0f, 0x2c, 0x3c, 0xb0, 0xdd, 0x91, 0x85, 0xc5, 0x3f,
	0xb6, 0x69, 0x33, 0x7b, 0xd3, 0xab, 0x50, 0x60, 0xf8, 0x33, 0x99, 0xdd, 0x0a, 0xd9, 0x2d, 0x89,
	0x5d, 0xff, 0x14, 0x66, 0x9e, 0xd9, 0x3d, 0xd3, 0x6a, 0xe1, 0x57, 0x3e, 0x39, 0x2b, 0xd2, 0xa0,
	0xea, 0xbb, 0xd8, 0xb1, 0x8c, 0x01, 0x6e, 0xe6, 0xd6, 0x73, 0x37, 0x6b, 0xad, 0xe8, 0x3b, 0xa0,
	0x0d, 0x0d, 0xd7, 0x7d, 0x63, 0x3b, 0x9d, 0x66, 0x3e, 0xa4, 0xf1, 0x6f, 0xfd, 0x29, 0xcc, 0x32,
	0x1c, 0x77, 0x68, 0x5b, 0x2e, 0x46, 0xff, 0x87, 0x19, 0xa3, 0xdd, 0xc6, 0xae, 0x7b, 0xe4, 0xd9,
	0xa7, 0xd8, 0xa2, 0x60, 0xf5, 0x9d, 0xe5, 0x2d, 0xa1, 0xde, 0x2e, 0x25, 0xbf, 0x0c, 0xa8, 0xad,
	0xba, 0x21, 0x3e, 0x18, 0x96, 0xed, 0x7b, 0xfc, 0x50, 0x7f, 0x01, 0x6b, 0x1e, 0x1a, 0x1c, 0x2b,
	0x3c, 0x98, 0x7e, 0x08, 0xcb, 0x07, 0xee, 0xae, 0xef, 0x9d, 0x60, 0xcb, 0x33, 0xdb, 0x86, 0x87,
	0x3b, 0xe7, 0x20, 0xe6, 0x11, 0xac, 0xa4, 0x40, 0x99, 0x21, 0xae, 0xc2, 0xac, 0x21, 0x13, 0x28,
	0x6c, 0xb5, 0x15, 0x5f, 0xd4, 0x3f, 0x87, 0xf9, 0x03, 0x77, 0xdf, 0x31, 0x2c, 0xe9, 0x3c, 0x2b,
	0x50, 0x09, 0x6c, 0x7f, 0x64, 0x86, 0x7b, 0x0a, 0xad, 0x72, 0xf0, 0x79, 0xd0, 0x41, 0x6b, 0x00,
	0x43, 0xec, 0x0c, 0x4c, 0xd7, 0x35, 0x6d, 0x8b, 0x5d, 0x85, 0xb4, 0xa2, 0x6f, 0xc2, 0x82, 0x04,
	0xc6, 0xce, 0xd1, 0x84, 0x4a, 0x2f, 0x5c, 0x62, 0x27, 0xe0, 0x9f, 0xc4, 0x07, 0xe6, 0xf7, 0x70,
	0xdf, 0xb6, 0x7a, 0x44, 0x99, 0x89, 0xb2, 0x2f, 0x42, 0xb5, 0xe7, 0xd8, 0xfe, 0x30, 0xa0, 0xe4,
	0x29, 0xa5, 0x42, 0xbf, 0x0f, 0x3a, 0x81, 0x58, 0x09, 0x47, 0x88, 0x3d, 0x0e, 0x17, 0xb9, 0x58,
	0xf6, 0x49, 0x54, 0x6e, 0x1c, 0xfa, 0xc7, 0x3f, 0xe0, 0xf6, 0x79, 0xdc, 0xf3, 0x4f, 0x79, 0x98,
	0x8b, 0xd0, 0x98, 0xe8, 0x06, 0xe4, 0xa3, 0xe3, 0x93, 0x7f, 0x31, 0xdf, 0xce, 0x27, 0x7c, 0xfb,
	0x32, 0x40, 0xd7, 0x74, 0x5c, 0xef, 0x88, 0x52, 0x0b, 0x94, 0x5a, 0xa3, 0x2b, 0xcf, 0x03, 0xf2,
	0x2a, 0xd4, 0xfa, 0x06, 0xa7, 0x16, 0xc3, 0xbd, 0xc1, 0x02, 0x25, 0xae, 0x43, 0x5d, 0x18, 0xdf,
	0x6d, 0x96, 0xd6, 0x0b, 0x84, 0x2c, 0x2f, 0xa1, 0x2b, 0x30, 0x63, 0xba, 0x47, 0xae, 0x4f, 0xd6,
	0x02, 0x89, 0xcd, 0x32, 0xb5, 0x44, 0xdd, 0x74, 0x0f, 0xf9, 0x52, 0x20, 0x81, 0xb0, 0x18, 0x6d,
	0xcf, 0x7c, 0x8d, 0x9b, 0x15, 0x4a, 0xaf, 0x9a, 0xee, 0x2e, 0xfd, 0x0e, 0x8c, 0x1e, 0xec, 0xf7,
	0xfc, 0x6e, 0xb7, 0x59, 0x0d, 0xad, 0x48, 0xf6, 0x06, 0x9f, 0x0c, 0xba, 0x6d, 0x5b, 0xe4, 0xb0,
	0x03, 0x72, 0xb7, 0x35, 0x0e, 0xfd, 0x98, 0x2f, 0xe9, 0xbf, 0x14, 0xa0, 0xf8, 0x55, 0x20, 0xe3,
	0x43, 0x19, 0x24, 0xa9, 0x6e, 0x69, 0x82, 0xba, 0xe5, 0x0c, 0x75, 0x0d, 0xa2, 0x6e, 0x45, 0xa8,
	0x6b, 0x28, 0xd4, 0xad, 0xa6, 0xd4, 0x25, 0x5e, 0x04, 0x6d, 0x07, 0x07, 0x51, 0x75, 0x64, 0x78,
	0xd4, 0x1e, 0xf5, 0x1d, 0x6d, 0xab, 0x67, 0xdb, 0xbd, 0x3e, 0xcb, 0xa9, 0x24, 0x59, 0x6f, 0xbd,
	0xe4, 0xb9, 0xb9, 0x55, 0x63, 0xdc, 0xbb, 0x1e, 0xba, 0x25, 0xb6, 0x1e, 0x8f, 0x9a, 0x40, 0xb7,
	0xce, 0x6e, 0xb1, 0x84, 0x79, 0x60, 0x79, 0x77, 0xff, 0x13, 0x71, 0xef, 0x8d, 0x02, 0x41, 0xfe,
	0xb0, 0xc3, 0x05, 0xd5, 0x27, 0x0b, 0x62, 0xdc, 0xa1, 0x20, 0xbe, 0x95, 0x08, 0x9a, 0x51, 0x0a,
	0x62, 0x0c, 0x7b, 0x23, 0xfd, 0x8f, 0x3c, 0x2c, 0x3c, 0xa6, 0x62, 0x83, 0x6b, 0x9c, 0x26, 0x55,
	0x5f, 0x83, 0xc6, 0xb0, 0x6f, 0x98, 0xd6, 0x51, 0x22, 0x61, 0xcf, 0xd2, 0xd5, 0x17, 0x6c, 0x11,
	0xdd, 0x80, 0x39, 0x17, 0xb7, 0x7d, 0x07, 0x0b, 0xbe, 0xe0, 0xa6, 0x67, 0x5a, 0x8d, 0x70, 0x39,
	0x62, 0x8c, 0x7b, 0x43, 0x71, 0xac, 0x37, 0x94, 0x12, 0xde, 0xb0, 0xad, 0x70, 0xfe, 0xfa, 0xce,
	0x0c, 0xd7, 0x76, 0xcf, 0xb6, 0xfb, 0x71, 0xdf, 0xf8, 0x47, 0x32, 0x14, 0x92, 0xdc, 0xc2, 0x53,
	0x6e, 0x48, 0x9e, 0x52, 0x55, 0x70, 0x46, 0x7e, 0xb3, 0xad, 0x08, 0x13, 0xc5, 0x21, 0x44, 0xd0,
	0xdc, 0x05, 0x24, 0x9b, 0x9c, 0xa5, 0x94, 0x75, 0x28, 0x52, 0x1d, 0x72, 0x6c, 0x3b, 0xab, 0x11,
	0x28, 0x0f, 0xa5, 0xe8, 0xeb, 0xd0, 0xd8, 0xc7, 0x9e, 0x7c, 0x4f, 0x89, 0xa8, 0xd3, 0xef, 0xc0,
	0x5c, 0xc4, 0x31, 0x35, 0xec, 0xef, 0x79, 0x98, 0x7f, 0x66, 0xba, 0x74, 0x9b, 0xcb, 0x91, 0x93,
	0x96, 0xcd, 0x4d, 0xb2, 0xac, 0x6c, 0xae, 0xfc, 0x38, 0x73, 0xc5, 0x03, 0xa1, 0xc0, 0xfc, 0xf3,
	0x55, 0x46, 0x20, 0x5c, 0x83, 0xb2, 0xdd, 0xed, 0xba, 0xd8, 0x6b, 0x76, 0x54, 0x9e, 0xcc, 0x88,
	0x68, 0x03, 0x4a, 0x7d, 0x73, 0x60, 0x7a, 0x4d, 0xac, 0xe2, 0x0a, 0x69, 0xe8, 0x2e, 0x14, 0x5d,
	0xdb, 0xf1, 0x9a, 0x5d, 0x92, 0x45, 0xeb, 0x3b, 0x3a, 0x37, 0x45, 0x52, 0xf7, 0xad, 0x43, 0xc2,
	0xf4, 0xc4, 0xf2, 0x9c, 0x51, 0x8b, 0xf2, 0x6b, 0xf7, 0xa0, 0x16, 0x2d, 0xa1, 0x79, 0x28, 0x9c,
	0xe2, 0x11, 0x8b, 0x8a, 0xe0, 0x2f, 0x5a, 0x84, 0xd2, 0x6b, 0xa3, 0xef, 0x87, 0x79, 0xae, 0xda,
	0x0a, 0x3f, 0xee, 0xe7, 0xff, 0x97, 0x7b, 0x5a, 0xac, 0x16, 0xe7, 0x3b, 0xfa, 0x3d, 0x58, 0x90,
	0x44, 0xb0, 0x6b, 0xd1, 0xa1, 0x14, 0x98, 0x2d, 0x78, 0xb9, 0x0a, 0xa9, 0x7b, 0x09, 0x49, 0xfa,
	0x06, 0x2c, 0x7c, 0x82, 0xfb, 0x38, 0x1e, 0x9a, 0xc9, 0x2b, 0xbf, 0x0d, 0x48, 0x66, 0x62, 0xf0,
	0x24, 0x80, 0x89, 0xad, 0xc9, 0x8b, 0x85, 0x39, 0x6f, 0xf4, 0xad, 0xff, 0x56, 0x80, 0x85, 0x2f,
	0xec, 0x8e, 0xd9, 0x1d, 0x8d, 0xc1, 0x45, 0xff, 0x4c, 0x24, 0xf0, 0xfa, 0x4e, 0x83, 0x1b, 0xf5,
	0xd0, 0x73, 0x4c, 0xab, 0x27, 0xa5, 0x84, 0xff, 0xa6, 0x52, 0x42, 0x41, 0xb9, 0x63, 0x72, 0x8a,
	0x28, 0x2a, 0x53, 0xc4, 0x66, 0x2c, 0x45, 0x94, 0x94, 0xd8, 0x52, 0xca, 0xf8, 0x97, 0x9c, 0x32,
	0xca, 0xea, 0xb3, 0x67, 0xa6, 0x90, 0xca, 0x99, 0x52, 0x48, 0x75, 0xea, 0x14, 0x52, 0x3b, 0x4b,
	0x0a, 0x81, 0x29, 0x52, 0x88, 0x7c, 0x85, 0x53, 0xc7, 0xfa, 0x2d, 0xd0, 0xb8, 0x2f, 0xbe, 0x10,
	0x45, 0x44, 0x96, 0x6f, 0x3d, 0x82, 0x55, 0x25, 0x77, 0x24, 0x2e, 0x56, 0x9c, 0xe4, 0x52, 0xc5,
	0x89, 0xfe, 0x35, 0x5c, 0x3c, 0xc4, 0x59, 0xd2, 0x32, 0xeb, 0xc0, 0x04, 0x6e, 0x3e, 0x8d, 0x6b,
	0x81, 0xa6, 0xc2, 0x15, 0x75, 0x21, 0x4b, 0x20, 0x0c, 0x98, 0x7f, 0x06, 0x14, 0x87, 0xd4, 0x7b,
	0xaf, 0x71, 0x54, 0x60, 0xb2, 0x4f, 0x74, 0x09, 0x6a, 0xbe, 0xe5, 0xd9, 0x7e, 0xfb, 0x04, 0x87,
	0xde, 0x5b, 0x68, 0x89, 0x05, 0xfd, 0x06, 0x2c, 0x71, 0x43, 0xec, 0x07, 0x15, 0xe9, 0x18, 0x8b,
	0x2d, 0x27, 0x19, 0xd9, 0xa1, 0x48, 0x22, 0xa3, 0xc5, 0x2c, 0x8f, 0xf8, 0x59, 0x7e, 0x3b, 0x94,
	0xaf, 0xc5, 0x88, 0xfa, 0x3e, 0x2c, 0x32, 0xcd, 0xe2, 0x82, 0x32, 0x8d, 0xb5, 0x1c, 0xe1, 0x06,
	0x76, 0x2a, 0x44, 0x40, 0x26, 0x2c, 0x25, 0x80, 0xde, 0x9b, 0x75, 0x3e, 0x02, 0xad, 0x85, 0x7b,
	0x44, 0x6d, 0xe5, 0x35, 0x4f, 0xf6, 0x12, 0x1b, 0x56, 0x95, 0xfb, 0xdf, 0xdb, 0x81, 0x7f, 0x2d,
	0x84, 0xd7, 0xa4, 0x38, 0xed, 0x2d, 0xa8, 0xb9, 0xfe, 0xb1, 0x3b, 0x22, 0x87, 0x19, 0xb0, 0x38,
	0x6a, 0xf0, 0xc7, 0x89, 0x67, 0x9a, 0x88, 0x01, 0x5d, 0x87, 0xf2, 0xc0, 0xee, 0xf8, 0x7d, 0x91,
	0x22, 0xe3, 0xac, 0x8c, 0x1a, 0xf0, 0x05, 0x09, 0x83, 0x74, 0x54, 0x05, 0x35, 0x5f, 0x48, 0x45,
	0xb7, 0x63, 0xf5, 0x65, 0x91, 0xf2, 0x2e, 0x70, 0xde, 0x29, 0xca, 0xca, 0xd2, 0x07, 0x7c, 0x4d,
	0x1f, 0xc6, 0x5e, 0xd3, 0x9b, 0xf2, 0x6b, 0x9a, 0xb6, 0xeb, 0x79, 0xbe, 0xa9, 0x65, 0xf2, 0xa6,
	0x3e, 0x80, 0x95, 0x94, 0xa0, 0xa9, 0xb3, 0xd2, 0x75, 0x58, 0x24, 0x55, 0x92, 0xd8, 0x9b, 0x15,
	0xcc, 0xf7, 0x60, 0x29, 0xc1, 0xc7, 0x44, 0xc4, 0x9b, 0xe4, 0x5c, 0xaa, 0x49, 0xfe, 0x39, 0x0f,
	0x25, 0x1a, 0x75, 0xa9, 0x57, 0x15, 0x41, 0x51, 0x6a, 0x89, 0xe8, 0xff, 0xe0, 0xc0, 0x1d, 0xec,
	0xb6, 0x1d, 0x73, 0x18, 0x79, 0x08, 0x39, 0xb0, 0xb4, 0x94, 0x68, 0x3b, 0x8a, 0xef, 0xde, 0x76,
	0x94, 0xce, 0xd4, 0x76, 0x94, 0xdf, 0xbd, 0xed, 0xa8, 0x4c, 0x68, 0x3b, 0xbe, 0xe5, 0x25, 0x70,
	0x98, 0xfd, 0xd8, 0x05, 0x70, 0xeb, 0xe4, 0x24, 0xeb, 0xdc, 0x8e, 0x5b, 0x47, 0x5d, 0x8a, 0xc8,
	0x2c, 0xfa, 0x7d, 0xb8, 0x10, 0xc3, 0x66, 0x97, 0x46, 0x9c, 0x9a, 0xa6, 0x46, 0x16, 0xd5, 0x89,
	0xfc, 0x1b, 0xd2, 0xf4, 0x2b, 0xb4, 0x80, 0x8e, 0x1d, 0x2a, 0xed, 0x15, 0xf3, 0x82, 0xe5, 0x2c,
	0xd8, 0x38, 0xac, 0x03, 0xe3, 0x79, 0xfd, 0x1c, 0x23, 0x92, 0x84, 0x46, 0x8e, 0x86, 0x06, 0x92,
	0xc5, 0x9c, 0xed, 0xf9, 0xb9, 0xca, 0xab, 0xc9, 0xb1, 0x26, 0xf8, 0x37, 0x5c, 0x88, 0x71, 0x4d,
	0x51, 0x74, 0xbe, 0xe5, 0x05, 0xcb, 0x38, 0x60, 0x52, 0x15, 0x17, 0xc7, 0x14, 0x9c, 0x4a, 0x87,
	0x28, 0x4c, 0xe5, 0x10, 0x31, 0xd9, 0x67, 0xb9, 0xb4, 0x6f, 0x68, 0xa5, 0x41, 0x97, 0x14, 0xaf,
	0x85, 0x3c, 0xb1, 0xca, 0xc5, 0x26, 0x56, 0x53, 0x14, 0x31, 0xe4, 0xd9, 0x53, 0x42, 0xbf, 0xb7,
	0x67, 0x6f, 0x33, 0x2c, 0xe7, 0xb2, 0x94, 0x49, 0xde, 0xf2, 0xc7, 0x70, 0x49, 0xcd, 0x3e, 0x6d,
	0xa2, 0xdd, 0xf9, 0x71, 0x0e, 0x0a, 0xad, 0x17, 0x8f, 0x49, 0xe3, 0x55, 0xa2, 0x13, 0x5c, 0xb4,
	0x18, 0xbd, 0x12, 0xd2, 0x60, 0x58, 0x5b, 0x4a, 0xac, 0xb2, 0x69, 0xea, 0xdf, 0x48, 0x3a, 0x2a,
	0x87, 0x13, 0x56, 0x24, 0xb3, 0x88, 0xe9, 0xad, 0xb6, 0x9c, 0x5c, 0x8e, 0xb6, 0xbe, 0x84, 0xb9,
	0xc4, 0xd4, 0x14, 0xad, 0x71, 0x66, 0xf5, 0x8c, 0x56, 0xfb, 0x7b, 0x26, 0x3d, 0x42, 0x7d, 0x08,
	0x15, 0x36, 0x09, 0x44, 0x91, 0xe8, 0xf8, 0xa0, 0x51, 0x5b, 0x49, 0xad, 0x47, 0xbb, 0xf7, 0xa0,
	0x16, 0xcd, 0x4e, 0x51, 0x53, 0x48, 0x8b, 0xcf, 0x66, 0xb5, 0x8b, 0x0a, 0x8a, 0x8c, 0x11, 0x0d,
	0x42, 0x05, 0x46, 0x72, 0xc6, 0x2a, 0x30, 0x52, 0x53, 0x53, 0x82, 0xf1, 0x04, 0x40, 0xcc, 0x1f,
	0x50, 0xc4, 0x9a, 0x1a, 0x03, 0x69, 0x9a, 0x8a, 0x24, 0xc3, 0x88, 0x1e, 0x44, 0xc0, 0xa4, 0x5a,
	0x4b, 0x01, 0x93, 0x6e, 0x59, 0x42, 0x9b, 0xb2, 0x99, 0x85, 0xb0, 0x69, 0x7c, 0xcc, 0x21, 0x6c,
	0x9a, 0x18, 0x6e, 0x84, 0xf6, 0x88, 0x9a, 0x6b, 0x61, 0x8f, 0x64, 0x4b, 0x2f, 0xec, 0x91, 0xea,
	0xc4, 0x43, 0x45, 0x44, 0x0b, 0x2d, 0x14, 0x49, 0xf5, 0xde, 0x42, 0x91, 0x74, 0xc7, 0x4d, 0x60,
	0xbe, 0x87, 0x0b, 0x8a, 0x6e, 0x09, 0xa5, 0xe6, 0x0c, 0xe9, 0xd0, 0xd3, 0x36, 0xc6, 0xf2, 0x44,
	0x12, 0xbe, 0x03, 0x94, 0x6e, 0x7b, 0xd0, 0x95, 0xc8, 0xe3, 0xb2, 0x5a, 0x2d, 0x4d, 0x1f, 0xc7,
	0x12, 0xc1, 0x7f, 0x09, 0x8d, 0x78, 0xf3, 0x82, 0x2e, 0x27, 0xcf, 0x15, 0x7b, 0xbc, 0xb4, 0xb5,
	0x2c, 0x72, 0x04, 0xf9, 0x1c, 0x66, 0x63, 0x5d, 0x08, 0xba, 0x94, 0x38, 0x49, 0x1c, 0xf0, 0x72,
	0x06, 0x55, 0xb6, 0xb1, 0xa2, 0x55, 0x10, 0x36, 0xce, 0xee, 0x43, 0x84, 0x8d, 0xc7, 0xf4, 0x1a,
	0x61, 0xe2, 0x48, 0x54, 0x96, 0x68, 0x6d, 0x7c, 0x6d, 0x2b, 0x12, 0x47, 0x46, 0x49, 0x1a, 0xda,
	0x21, 0x56, 0x4a, 0x0a, 0x3b, 0xa8, 0x2a, 0x51, 0x61, 0x07, 0x65, 0xfd, 0x49, 0xf0, 0x3e, 0x83,
	0xba, 0x54, 0xe3, 0xa0, 0x44, 0xa0, 0xca, 0x6f, 0xac, 0xb6, 0xaa, 0xa4, 0xc9, 0x48, 0xd2, 0xe3,
	0x88, 0x12, 0xb1, 0xaa, 0x46, 0x52, 0xbc, 0xa6, 0x04, 0xe9, 0x11, 0x54, 0x79, 0x61, 0x84, 0xe4,
	0x88, 0x8d, 0x61, 0x34, 0xd3, 0x04, 0x39, 0x0e, 0x45, 0xe5, 0x82, 0x62, 0x21, 0x1b, 0x77, 0x13,
	0x4d, 0x45, 0x92, 0x35, 0x92, 0xaa, 0x13, 0x94, 0x08, 0x5a, 0xb5, 0x46, 0x8a, 0x72, 0x86, 0x20,
	0xb5, 0x61, 0x51, 0xf5, 0x02, 0xa2, 0x8d, 0x94, 0x7c, 0x85, 0x57, 0x5c, 0x1d, 0xcf, 0x24, 0xbb,
	0xb4, 0xa2, 0x0c, 0x40, 0x72, 0xc8, 0x66, 0x89, 0xd8, 0x18, 0xcb, 0xc3, 0x25, 0x1c, 0x97, 0x69,
	0xe5, 0x7e, 0xe7, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x91, 0xc3, 0x39, 0x77, 0x1e, 0x00,
	0x00,
}
