// Code generated by mockery v1.0.0. DO NOT EDIT.

package charondmock

import charond "github.com/piotrkowalczuk/charon/pb/rpc/charond/v1"
import context "context"
import mock "github.com/stretchr/testify/mock"

// PermissionManagerServer is an autogenerated mock type for the PermissionManagerServer type
type PermissionManagerServer struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *PermissionManagerServer) Get(_a0 context.Context, _a1 *charond.GetPermissionRequest) (*charond.GetPermissionResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *charond.GetPermissionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.GetPermissionRequest) *charond.GetPermissionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.GetPermissionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.GetPermissionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *PermissionManagerServer) List(_a0 context.Context, _a1 *charond.ListPermissionsRequest) (*charond.ListPermissionsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *charond.ListPermissionsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.ListPermissionsRequest) *charond.ListPermissionsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.ListPermissionsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.ListPermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *PermissionManagerServer) Register(_a0 context.Context, _a1 *charond.RegisterPermissionsRequest) (*charond.RegisterPermissionsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *charond.RegisterPermissionsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.RegisterPermissionsRequest) *charond.RegisterPermissionsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.RegisterPermissionsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.RegisterPermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
