// Code generated by mockery v1.0.0. DO NOT EDIT.

package charondmock

import charond "github.com/piotrkowalczuk/charon/pb/rpc/charond/v1"
import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"

// RefreshTokenManagerClient is an autogenerated mock type for the RefreshTokenManagerClient type
type RefreshTokenManagerClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *RefreshTokenManagerClient) Create(ctx context.Context, in *charond.CreateRefreshTokenRequest, opts ...grpc.CallOption) (*charond.CreateRefreshTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *charond.CreateRefreshTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.CreateRefreshTokenRequest, ...grpc.CallOption) *charond.CreateRefreshTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.CreateRefreshTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.CreateRefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *RefreshTokenManagerClient) List(ctx context.Context, in *charond.ListRefreshTokensRequest, opts ...grpc.CallOption) (*charond.ListRefreshTokensResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *charond.ListRefreshTokensResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.ListRefreshTokensRequest, ...grpc.CallOption) *charond.ListRefreshTokensResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.ListRefreshTokensResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.ListRefreshTokensRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, in, opts
func (_m *RefreshTokenManagerClient) Revoke(ctx context.Context, in *charond.RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*charond.RevokeRefreshTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *charond.RevokeRefreshTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *charond.RevokeRefreshTokenRequest, ...grpc.CallOption) *charond.RevokeRefreshTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*charond.RevokeRefreshTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *charond.RevokeRefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
