// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/group.proto

package charond // import "github.com/piotrkowalczuk/charon/pb/rpc/charond/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import ntypes "github.com/piotrkowalczuk/ntypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Group struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *ntypes.Int64        `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *ntypes.Int64        `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{0}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Group) GetCreatedBy() *ntypes.Int64 {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *Group) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Group) GetUpdatedBy() *ntypes.Int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

type CreateGroupRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          *ntypes.String `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{1}
}
func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(dst, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetDescription() *ntypes.String {
	if m != nil {
		return m.Description
	}
	return nil
}

type CreateGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{2}
}
func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (dst *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(dst, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GetGroupRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{3}
}
func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (dst *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(dst, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{4}
}
func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (dst *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(dst, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListGroupsRequest struct {
	Offset               *ntypes.Int64 `protobuf:"bytes,100,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                *ntypes.Int64 `protobuf:"bytes,101,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy              []*Order      `protobuf:"bytes,102,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{5}
}
func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(dst, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetOffset() *ntypes.Int64 {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ListGroupsRequest) GetLimit() *ntypes.Int64 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListGroupsRequest) GetOrderBy() []*Order {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

type ListGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{6}
}
func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(dst, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{7}
}
func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(dst, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ModifyGroupRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *ntypes.String `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *ntypes.String `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ModifyGroupRequest) Reset()         { *m = ModifyGroupRequest{} }
func (m *ModifyGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyGroupRequest) ProtoMessage()    {}
func (*ModifyGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{8}
}
func (m *ModifyGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGroupRequest.Unmarshal(m, b)
}
func (m *ModifyGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGroupRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGroupRequest.Merge(dst, src)
}
func (m *ModifyGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyGroupRequest.Size(m)
}
func (m *ModifyGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGroupRequest proto.InternalMessageInfo

func (m *ModifyGroupRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyGroupRequest) GetName() *ntypes.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyGroupRequest) GetDescription() *ntypes.String {
	if m != nil {
		return m.Description
	}
	return nil
}

type ModifyGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyGroupResponse) Reset()         { *m = ModifyGroupResponse{} }
func (m *ModifyGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyGroupResponse) ProtoMessage()    {}
func (*ModifyGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{9}
}
func (m *ModifyGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGroupResponse.Unmarshal(m, b)
}
func (m *ModifyGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGroupResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGroupResponse.Merge(dst, src)
}
func (m *ModifyGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyGroupResponse.Size(m)
}
func (m *ModifyGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGroupResponse proto.InternalMessageInfo

func (m *ModifyGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type SetGroupPermissionsRequest struct {
	GroupId     int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Force tells if permission should be created in case if it does not exists.
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupPermissionsRequest) Reset()         { *m = SetGroupPermissionsRequest{} }
func (m *SetGroupPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*SetGroupPermissionsRequest) ProtoMessage()    {}
func (*SetGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{10}
}
func (m *SetGroupPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupPermissionsRequest.Unmarshal(m, b)
}
func (m *SetGroupPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *SetGroupPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupPermissionsRequest.Merge(dst, src)
}
func (m *SetGroupPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_SetGroupPermissionsRequest.Size(m)
}
func (m *SetGroupPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupPermissionsRequest proto.InternalMessageInfo

func (m *SetGroupPermissionsRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *SetGroupPermissionsRequest) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *SetGroupPermissionsRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type SetGroupPermissionsResponse struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Removed              int64    `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	Untouched            int64    `protobuf:"varint,3,opt,name=untouched,proto3" json:"untouched,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupPermissionsResponse) Reset()         { *m = SetGroupPermissionsResponse{} }
func (m *SetGroupPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*SetGroupPermissionsResponse) ProtoMessage()    {}
func (*SetGroupPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{11}
}
func (m *SetGroupPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupPermissionsResponse.Unmarshal(m, b)
}
func (m *SetGroupPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *SetGroupPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupPermissionsResponse.Merge(dst, src)
}
func (m *SetGroupPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_SetGroupPermissionsResponse.Size(m)
}
func (m *SetGroupPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupPermissionsResponse proto.InternalMessageInfo

func (m *SetGroupPermissionsResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SetGroupPermissionsResponse) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *SetGroupPermissionsResponse) GetUntouched() int64 {
	if m != nil {
		return m.Untouched
	}
	return 0
}

type ListGroupPermissionsRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupPermissionsRequest) Reset()         { *m = ListGroupPermissionsRequest{} }
func (m *ListGroupPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupPermissionsRequest) ProtoMessage()    {}
func (*ListGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{12}
}
func (m *ListGroupPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupPermissionsRequest.Unmarshal(m, b)
}
func (m *ListGroupPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListGroupPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupPermissionsRequest.Merge(dst, src)
}
func (m *ListGroupPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupPermissionsRequest.Size(m)
}
func (m *ListGroupPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupPermissionsRequest proto.InternalMessageInfo

func (m *ListGroupPermissionsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListGroupPermissionsResponse struct {
	Permissions          []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupPermissionsResponse) Reset()         { *m = ListGroupPermissionsResponse{} }
func (m *ListGroupPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupPermissionsResponse) ProtoMessage()    {}
func (*ListGroupPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_a1b9c6fb366f15a1, []int{13}
}
func (m *ListGroupPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupPermissionsResponse.Unmarshal(m, b)
}
func (m *ListGroupPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroupPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupPermissionsResponse.Merge(dst, src)
}
func (m *ListGroupPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupPermissionsResponse.Size(m)
}
func (m *ListGroupPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupPermissionsResponse proto.InternalMessageInfo

func (m *ListGroupPermissionsResponse) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Group)(nil), "charon.rpc.charond.v1.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "charon.rpc.charond.v1.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "charon.rpc.charond.v1.CreateGroupResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "charon.rpc.charond.v1.GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "charon.rpc.charond.v1.GetGroupResponse")
	proto.RegisterType((*ListGroupsRequest)(nil), "charon.rpc.charond.v1.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "charon.rpc.charond.v1.ListGroupsResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "charon.rpc.charond.v1.DeleteGroupRequest")
	proto.RegisterType((*ModifyGroupRequest)(nil), "charon.rpc.charond.v1.ModifyGroupRequest")
	proto.RegisterType((*ModifyGroupResponse)(nil), "charon.rpc.charond.v1.ModifyGroupResponse")
	proto.RegisterType((*SetGroupPermissionsRequest)(nil), "charon.rpc.charond.v1.SetGroupPermissionsRequest")
	proto.RegisterType((*SetGroupPermissionsResponse)(nil), "charon.rpc.charond.v1.SetGroupPermissionsResponse")
	proto.RegisterType((*ListGroupPermissionsRequest)(nil), "charon.rpc.charond.v1.ListGroupPermissionsRequest")
	proto.RegisterType((*ListGroupPermissionsResponse)(nil), "charon.rpc.charond.v1.ListGroupPermissionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupManagerClient is the client API for GroupManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupManagerClient interface {
	Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	Modify(ctx context.Context, in *ModifyGroupRequest, opts ...grpc.CallOption) (*ModifyGroupResponse, error)
	Get(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	List(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	ListPermissions(ctx context.Context, in *ListGroupPermissionsRequest, opts ...grpc.CallOption) (*ListGroupPermissionsResponse, error)
	SetPermissions(ctx context.Context, in *SetGroupPermissionsRequest, opts ...grpc.CallOption) (*SetGroupPermissionsResponse, error)
}

type groupManagerClient struct {
	cc *grpc.ClientConn
}

func NewGroupManagerClient(cc *grpc.ClientConn) GroupManagerClient {
	return &groupManagerClient{cc}
}

func (c *groupManagerClient) Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) Modify(ctx context.Context, in *ModifyGroupRequest, opts ...grpc.CallOption) (*ModifyGroupResponse, error) {
	out := new(ModifyGroupResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) Get(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) List(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) ListPermissions(ctx context.Context, in *ListGroupPermissionsRequest, opts ...grpc.CallOption) (*ListGroupPermissionsResponse, error) {
	out := new(ListGroupPermissionsResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/ListPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagerClient) SetPermissions(ctx context.Context, in *SetGroupPermissionsRequest, opts ...grpc.CallOption) (*SetGroupPermissionsResponse, error) {
	out := new(SetGroupPermissionsResponse)
	err := c.cc.Invoke(ctx, "/charon.rpc.charond.v1.GroupManager/SetPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupManagerServer is the server API for GroupManager service.
type GroupManagerServer interface {
	Create(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	Modify(context.Context, *ModifyGroupRequest) (*ModifyGroupResponse, error)
	Get(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	List(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	Delete(context.Context, *DeleteGroupRequest) (*wrappers.BoolValue, error)
	ListPermissions(context.Context, *ListGroupPermissionsRequest) (*ListGroupPermissionsResponse, error)
	SetPermissions(context.Context, *SetGroupPermissionsRequest) (*SetGroupPermissionsResponse, error)
}

func RegisterGroupManagerServer(s *grpc.Server, srv GroupManagerServer) {
	s.RegisterService(&_GroupManager_serviceDesc, srv)
}

func _GroupManager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).Create(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).Modify(ctx, req.(*ModifyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).Get(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).List(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).Delete(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/ListPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).ListPermissions(ctx, req.(*ListGroupPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManager_SetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagerServer).SetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/charon.rpc.charond.v1.GroupManager/SetPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagerServer).SetPermissions(ctx, req.(*SetGroupPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "charon.rpc.charond.v1.GroupManager",
	HandlerType: (*GroupManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GroupManager_Create_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _GroupManager_Modify_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GroupManager_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GroupManager_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GroupManager_Delete_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _GroupManager_ListPermissions_Handler,
		},
		{
			MethodName: "SetPermissions",
			Handler:    _GroupManager_SetPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/group.proto",
}

func init() {
	proto.RegisterFile("github.com/piotrkowalczuk/charon/pb/rpc/charond/v1/group.proto", fileDescriptor_group_a1b9c6fb366f15a1)
}

var fileDescriptor_group_a1b9c6fb366f15a1 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6b, 0x4f, 0xdc, 0x46,
	0x14, 0xc5, 0xeb, 0x7d, 0x71, 0x69, 0x81, 0x0e, 0xad, 0xe4, 0x1a, 0xd4, 0x6e, 0xdd, 0xd7, 0x52,
	0xb5, 0x76, 0x59, 0x50, 0xab, 0x36, 0x52, 0x1e, 0x9b, 0x28, 0x08, 0x14, 0x14, 0x62, 0xa2, 0x28,
	0x42, 0x8a, 0x88, 0xd7, 0x9e, 0x5d, 0x2c, 0xd6, 0x1e, 0x67, 0x3c, 0x06, 0x19, 0xe5, 0xb7, 0x24,
	0xbf, 0x2b, 0xff, 0x26, 0xf2, 0x78, 0xec, 0x7d, 0xd8, 0xe6, 0x11, 0x3e, 0xb1, 0x33, 0x73, 0xee,
	0x3d, 0xf7, 0xdc, 0x7b, 0x66, 0x30, 0xdc, 0x1f, 0xb9, 0xec, 0x34, 0x1a, 0xe8, 0x36, 0xf1, 0x8c,
	0xc0, 0x25, 0x8c, 0x9e, 0x91, 0x0b, 0x6b, 0x6c, 0x5f, 0x46, 0x67, 0x86, 0x7d, 0x6a, 0x51, 0xe2,
	0x1b, 0xc1, 0xc0, 0xa0, 0x81, 0x2d, 0x56, 0x8e, 0x71, 0xbe, 0x65, 0x8c, 0x28, 0x89, 0x02, 0x3d,
	0xa0, 0x84, 0x11, 0xf4, 0x5d, 0xba, 0xaf, 0xd3, 0xc0, 0xd6, 0x05, 0x44, 0x3f, 0xdf, 0x52, 0x7f,
	0x1c, 0x11, 0x32, 0x1a, 0x63, 0x83, 0x83, 0x06, 0xd1, 0xd0, 0x60, 0xae, 0x87, 0x43, 0x66, 0x79,
	0x22, 0x4e, 0xfd, 0x61, 0x1e, 0x70, 0x41, 0xad, 0x20, 0xc0, 0x34, 0x14, 0xe7, 0x0f, 0xbe, 0xa0,
	0x2e, 0x9b, 0x78, 0x1e, 0xf1, 0x45, 0x82, 0x35, 0x9f, 0xc5, 0x01, 0x0e, 0x8d, 0xf4, 0x4f, 0xba,
	0xa9, 0x7d, 0xac, 0x41, 0x63, 0x37, 0xa9, 0x1e, 0x2d, 0x43, 0xcd, 0x75, 0x14, 0xa9, 0x23, 0x75,
	0x65, 0xb3, 0xe6, 0x3a, 0x08, 0x41, 0xdd, 0xb7, 0x3c, 0xac, 0xd4, 0x3a, 0x52, 0x77, 0xd1, 0xe4,
	0xbf, 0x51, 0x07, 0x96, 0x1c, 0x1c, 0xda, 0xd4, 0x0d, 0x98, 0x4b, 0x7c, 0x45, 0xe6, 0x47, 0xd3,
	0x5b, 0xe8, 0x3f, 0x00, 0x9b, 0x62, 0x8b, 0x61, 0xe7, 0xc4, 0x62, 0x4a, 0xbd, 0x23, 0x75, 0x97,
	0x7a, 0xaa, 0x9e, 0x4a, 0xd3, 0x33, 0x69, 0xfa, 0xcb, 0x4c, 0xbb, 0xb9, 0x28, 0xd0, 0x8f, 0x18,
	0xfa, 0x73, 0x12, 0x3a, 0x88, 0x95, 0x06, 0x0f, 0xfd, 0x5a, 0x17, 0xd5, 0xee, 0xf9, 0xec, 0x9f,
	0x9d, 0x1c, 0xdd, 0x8f, 0x13, 0xa2, 0x28, 0x70, 0x32, 0xa2, 0xe6, 0xf5, 0x44, 0x02, 0x9d, 0x12,
	0x65, 0xa1, 0x83, 0x58, 0x69, 0x95, 0x12, 0x09, 0x40, 0x3f, 0xd6, 0x8e, 0x01, 0x3d, 0xe6, 0xac,
	0xbc, 0x4d, 0x26, 0x7e, 0x17, 0xe1, 0x90, 0xe5, 0xdd, 0x91, 0xa6, 0xba, 0xf3, 0xf7, 0x6c, 0x77,
	0x6a, 0x3c, 0xf1, 0x72, 0x96, 0xf8, 0x88, 0x51, 0xd7, 0x1f, 0xcd, 0x74, 0x4b, 0xdb, 0x83, 0xb5,
	0x99, 0xdc, 0x61, 0x40, 0xfc, 0x10, 0xa3, 0x1e, 0x34, 0xb8, 0xa3, 0x78, 0xf6, 0xa5, 0xde, 0x86,
	0x5e, 0x6a, 0x29, 0x3d, 0x0d, 0x4a, 0xa1, 0xda, 0x4f, 0xb0, 0xb2, 0x8b, 0xd9, 0x4c, 0x8d, 0x73,
	0x13, 0xd5, 0x9e, 0xc2, 0xea, 0x04, 0x72, 0x07, 0xaa, 0x0f, 0x12, 0x7c, 0xf3, 0xcc, 0x0d, 0xd3,
	0x4c, 0x61, 0xc6, 0xf6, 0x2b, 0x34, 0xc9, 0x70, 0x18, 0x62, 0xa6, 0x38, 0x65, 0x1d, 0x15, 0x87,
	0xe8, 0x67, 0x68, 0x8c, 0x5d, 0xcf, 0x65, 0x0a, 0x2e, 0x43, 0xa5, 0x67, 0xe8, 0x5f, 0x68, 0x13,
	0xea, 0x60, 0x9a, 0xcc, 0x67, 0xd8, 0x91, 0xaf, 0x28, 0xec, 0x79, 0x02, 0x33, 0x5b, 0x1c, 0xdd,
	0x8f, 0xf7, 0xeb, 0x6d, 0x69, 0xd5, 0xd1, 0xf6, 0x01, 0x4d, 0xd7, 0x27, 0xa4, 0xee, 0x40, 0x93,
	0xd7, 0x1f, 0x2a, 0xd2, 0x95, 0x29, 0x53, 0xad, 0x02, 0xab, 0xfd, 0x02, 0xe8, 0x09, 0x1e, 0xe3,
	0xb9, 0xf1, 0xcf, 0xb7, 0xf6, 0x12, 0xd0, 0x01, 0x71, 0xdc, 0x61, 0x7c, 0x15, 0x0a, 0x69, 0x53,
	0x57, 0xaa, 0xe8, 0x8c, 0x52, 0x13, 0xc9, 0x37, 0x32, 0xd1, 0x0c, 0xf7, 0x1d, 0x26, 0x4b, 0x40,
	0x3d, 0x12, 0x0e, 0x39, 0xc4, 0xd4, 0x73, 0xc3, 0xd0, 0x25, 0x7e, 0x3e, 0xe1, 0xef, 0xa1, 0xcd,
	0x61, 0x27, 0xb9, 0xa8, 0x16, 0x5f, 0xef, 0x39, 0xc9, 0xc3, 0x10, 0x4c, 0x02, 0x94, 0x5a, 0x47,
	0x4e, 0x1e, 0x86, 0xa9, 0x2d, 0xf4, 0x2d, 0x34, 0x86, 0x84, 0xda, 0x98, 0x2b, 0x6a, 0x9b, 0xe9,
	0x42, 0x23, 0xb0, 0x5e, 0x4a, 0x28, 0x34, 0x28, 0xd0, 0x12, 0x37, 0x3e, 0x23, 0x14, 0xcb, 0xe4,
	0x84, 0x62, 0x8f, 0x9c, 0x63, 0x87, 0x77, 0x53, 0x36, 0xb3, 0x25, 0xda, 0x80, 0xc5, 0xc8, 0x67,
	0x24, 0xb2, 0x4f, 0xb1, 0xc3, 0xc9, 0x64, 0x73, 0xb2, 0xa1, 0xfd, 0x05, 0xeb, 0xb9, 0x35, 0x4a,
	0x24, 0xce, 0xcf, 0xf5, 0x21, 0x6c, 0x94, 0xc3, 0x45, 0x81, 0x73, 0xba, 0xa5, 0x82, 0xee, 0xde,
	0xa7, 0x06, 0x7c, 0xc5, 0xc3, 0x0f, 0x2c, 0xdf, 0x1a, 0x61, 0x8a, 0x2c, 0x68, 0xa6, 0x77, 0x1e,
	0x6d, 0x56, 0x8c, 0xa4, 0xf8, 0xdc, 0xa8, 0x7f, 0xdc, 0x04, 0x9a, 0xd6, 0xa4, 0x2d, 0x24, 0x14,
	0xa9, 0x23, 0x2a, 0x29, 0x8a, 0x66, 0xad, 0xa4, 0x28, 0xf1, 0x96, 0xb6, 0x80, 0x5e, 0x83, 0xbc,
	0x8b, 0x19, 0xfa, 0xad, 0xca, 0x55, 0xb3, 0x4f, 0x91, 0xfa, 0xfb, 0xb5, 0xb8, 0x3c, 0xf3, 0x1b,
	0xa8, 0x27, 0x2d, 0x47, 0xdd, 0x8a, 0x90, 0xc2, 0xcb, 0xa3, 0x6e, 0xde, 0x00, 0x99, 0xa7, 0x7f,
	0x01, 0xcd, 0xf4, 0x3e, 0x57, 0xf6, 0xa6, 0x78, 0xdd, 0xd5, 0xe2, 0x3f, 0x96, 0x3e, 0x21, 0xe3,
	0x57, 0xd6, 0x38, 0x4a, 0x52, 0xbe, 0x87, 0x95, 0x84, 0x6a, 0xca, 0x1f, 0xa8, 0x77, 0x5d, 0x49,
	0x45, 0xef, 0xa9, 0xdb, 0xb7, 0x8a, 0xc9, 0x05, 0xc5, 0xb0, 0x7c, 0x84, 0x67, 0xc8, 0xb7, 0x2a,
	0x12, 0x55, 0x5f, 0x6d, 0xb5, 0x77, 0x9b, 0x90, 0x8c, 0xba, 0xff, 0x16, 0x3a, 0x36, 0xf1, 0xf4,
	0xec, 0xc3, 0xa4, 0x2c, 0xc3, 0xa1, 0x74, 0xfc, 0xff, 0xed, 0x3f, 0x5c, 0xee, 0x89, 0x9f, 0x83,
	0x26, 0x6f, 0xf8, 0xf6, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x7a, 0x66, 0x78, 0x95, 0x09,
	0x00, 0x00,
}
